### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#110]
https://hastebin.com/onucozixir.cs

**Comment by LoneDev6** [comment]
please reupload the error, it's blank page

**Comment by 100petr** [comment]
```19:04:10] [Server thread/ERROR]: Could not pass event SignChangeEvent to ItemsAdder v2.0.6
dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Exception while getting NBTCompound from TileEntity!
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(SourceFile:179) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTTileEntity.getCompound(SourceFile:32) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.setData(SourceFile:468) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTCompound.setBoolean(SourceFile:268) ~[?:?]
	at dev.lone.itemsadder.f.b.b(SourceFile:24) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-155]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-155]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-155]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2586) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:44) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PacketPlayInUpdateSign.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-155]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-155]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Error while calling the method 'save', loaded: true, Enum: TILEENTITY_GET_NBT
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:150) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(SourceFile:174) ~[?:?]
	... 22 more
Caused by: java.lang.NullPointerException
	at sun.reflect.GeneratedMethodAccessor138.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:148) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.getTileEntityNBTTagCompound(SourceFile:174) ~[?:?]
	... 22 more```

**Comment by LoneDev6** [comment]
Will fix in next update, thanks!

**Comment by LoneDev6** [comment]
Reopen this if error still occurs in next update
