### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#112]
I don't know why its happens but sometimes the thist/manabar stop working and i got some nullpointers in the console

`[23:42:51 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.0.6
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.a(SourceFile:108) ~[?:?]
	at dev.lone.itemsadder.d.d.c.a.l.a(SourceFile:23) ~[?:?]
	at dev.lone.itemsadder.d.d.c.a.a.a.a(SourceFile:31) ~[?:?]
	at dev.lone.itemsadder.d.d.c.a.a.a.c(SourceFile:40) ~[?:?]
	at dev.lone.itemsadder.d.d.c.b.g.e(SourceFile:165) ~[?:?]
	at dev.lone.itemsadder.d.d.c.b.g.i(SourceFile:61) ~[?:?]
	at dev.lone.itemsadder.d.d.c.b.a(SourceFile:84) ~[?:?]
	at dev.lone.itemsadder.d.d.c.b.j(SourceFile:95) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-145]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:426) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1421) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-145]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by D3nied** [comment]
`[00:42:20 ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v2.0.6
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.b(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.c(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.a(SourceFile:238) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-145]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-145]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-145]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-145]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

and here another one

**Comment by LoneDev6** [comment]
are your players drinking from waterskin when this happens?

**Comment by derMiepz** [comment]
Heya o/ Different person, same server :D 
Not sure, but we'll keep an eye on it. Do you have any ideas about the second NullPtr? It's temporarily fixed when restarting the server but that's no long-term solution. :/

**Comment by D3nied** [comment]
little update we didn't saw the PlayerInteract Nullpointer since last update but the on Join is still happening `[23:47:16 ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v2.0.7
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.b(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.c(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.a(SourceFile:238) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-161]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-161]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-161]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.PlayerList.a(PlayerList.java:192) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:174) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:65) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:256) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1269) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by LoneDev6** [comment]
Thanks I will fix this in the upcoming update

**Comment by LoneDev6** [comment]
> PlayerJoinEvent

is it spamming everytime or only one time?

**Comment by derMiepz** [comment]
The message appears once, every time a player joins the server.

**Comment by LoneDev6** [comment]
> 
> 
> The message appears once, every time a player joins the server.

Did you disable huds?

**Comment by derMiepz** [comment]
It's a bit difficult to get a full server log, since they're divided among several files but here's a log with the complete start and the error in it https://pastebin.com/yPDTAtj5

**Comment by LoneDev6** [comment]
I see it doesn't happen everytime a user join, strange

**Comment by derMiepz** [comment]
Yeah right it doesn't happen for everyone on the server but IF it happens once for a specific user, it happens every time they join. Server restart fixes it temporarily. Do you have any idea why this is happening?

**Comment by LoneDev6** [comment]
> 
> 
> Yeah right it doesn't happen for everyone on the server but IF it happens once for a specific user, it happens every time they join. Server restart fixes it temporarily. Do you have any idea why this is happening?

Ohhh okok, now it's more clear.
Seems it fails to load a file for the current user.
Please can you check if a file with UUID of the bugged user is inside folder: plugins\ItemsAdder\storage\players\stats

**Comment by LoneDev6** [comment]
> 
> 
> Yeah right it doesn't happen for everyone on the server but IF it happens once for a specific user, it happens every time they join. Server restart fixes it temporarily. Do you have any idea why this is happening?

fixed in new version, I will publish it later ;) thanks!

reopen this if the issue will not be fixed for you
