### ISSUE TITLE
Items properties / tutorial error ?

### ISSUE THREAD

**Issue by yttalium** [LoneDev6/ItemsAdder#120]
Bonjour,
Again sorry for my English :sweat_smile: 

Problem test on 2.0.7 and 2.0.8. under paper#162

I wanted to create an item like "Healing Crystals" which gives 2 potion effects but unfortunately it does not work even following the tutorial and no error in the console, just no effect is given but the rest of the Actions work . To test a little I copied / pasted the tutorial and even it does not work however it shows me a console error. 
I also tried putting 2 particle effects with the same technique, it showed me the same error as with the sounds

**What I wanted to do**
```
kelvar_ring:
    display_name: Anneau de Kelvar
    permission: default
    resource:
      material: IRON_SWORD
      generate: true
      textures:
      - item/kelvar_ring.png
    durability:
      max_custom_durability: 5
      custom_durability: 5
      disappear_when_broken: true
    item_flags:
    - HIDE_ATTRIBUTES
    events:
      interact:
        right:
          play_particle:
            name: FLAME
          decrement_durability:
            amount: 1
          potion_effect_first:
            type: FIRE_RESISTANCE
            duration: 3600
            amplifier: 5
          potion_effect_second:
            type: ABSORPTION
            duration: 3600
            amplifier: 2
```

**My test using the tutorial**
```
kelvar_ring:
    display_name: Anneau de Kelvar
    permission: default
    resource:
      material: IRON_SWORD
      generate: true
      textures:
      - item/kelvar_ring.png
    durability:
      max_custom_durability: 5
      custom_durability: 5
      disappear_when_broken: true
    item_flags:
    - HIDE_ATTRIBUTES
    events:
      interact:
        right:
          play_sound_first:                   #
            name: itemsadder:ambient.creepy   # From the tutorial 
            volume: 1                         #  
            pitch: 1                          # >Plugin usage
          play_sound_second:                  #   >Adding content
            name: minecraft:ambient.cave      #     >Item properties
            volume: 1                         #       >Events
            pitch: 1                          #         >Actions
          play_particle:
            name: FLAME
          decrement_durability:
            amount: 1
          potion_effect:
            type: FIRE_RESISTANCE
            duration: 3600
            amplifier: 5
```
**And the error with the tutorial**

```
[13:10:39 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.0.8
java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.Particle.valueOf(Particle.java:9) ~[patched_1.15.2.jar:git-Paper-143]
        at dev.lone.itemsadder.d.d.c.a.p.a(SourceFile:22) ~[?:?]
        at dev.lone.itemsadder.d.d.c.a.a.a.a(SourceFile:31) ~[?:?]
        at dev.lone.itemsadder.d.d.c.a.a.a.c(SourceFile:40) ~[?:?]
        at dev.lone.itemsadder.d.d.c.b.g.e(SourceFile:165) ~[?:?]
        at dev.lone.itemsadder.d.d.c.b.g.i(SourceFile:61) ~[?:?]
        at dev.lone.itemsadder.d.d.c.b.a(SourceFile:84) ~[?:?]
        at dev.lone.itemsadder.d.d.c.b.j(SourceFile:95) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-143]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[patched_1.15.2.jar:git-Paper-143]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:426) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1421) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-143]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-143]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

Bonne journée en espérant que cela soit utile.

**Comment by LoneDev6** [comment]
Thanks a lot!
I fixed this problem in the next update, I will publish it later.
Please reopen this issue if problem won't be fixed for you in next update ;)

Thanks again
