### ISSUE TITLE
A Question and some suggestions

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#122]
Hey, fist of all thx for fixing the OnJoinBug

so this time i got some questions and suggestions, and maybe a bug  :D

The first question is bread and other normal vanilla foods fill up water. Is there a way to change the amount 
because I didn't find anything. There#s a chance that I skipped it tho.

So now the bug:
So the other thing with thirst is that it seems that the plugin doesn't recognize the nether as biome:

          

  biome_over_time_nether:
            min_sky_light: 1
            max_sky_light: 15
            biome: NETHER
            every_ticks: 600
            amount:  0.5

			
			
doesn't work as intended
The other thing is a info from a plugin called LagMonitor			

`[22:29:02 WARN]: [LagMonitor] Loaded class dev.lone.itemsadder.b.d from ItemsAdder v2.0.9 which is not a depend, softdepend or loadbefore of this plugin.
[22:29:02 WARN]: [LagMonitor] Plugin ItemsAdder is performing a blocking I/O operation on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. Besides gameplay performance it could also improve startup time. Keep in mind to keep the code thread-safe. Report it to the plugin author
[22:29:02 WARN]: [LagMonitor] The following exception is not an error. It's a hint for the plugin developer to find the source. LagMonitor doesn't prevent this action. It just warns you about it. 
java.lang.IllegalAccessException: null
	at com.github.games647.lagmonitor.threading.BlockingActionManager.logCurrentStack(BlockingActionManager.java:65) ~[?:?]
	at com.github.games647.lagmonitor.threading.BlockingActionManager.checkBlockingAction(BlockingActionManager.java:51) ~[?:?]
	at com.github.games647.lagmonitor.listener.BlockingConnectionSelector.select(BlockingConnectionSelector.java:30) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_241]
	at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at dev.lone.itemsadder.b.d.a(SourceFile:158) ~[?:?]
	at dev.lone.itemsadder.b.d.a(SourceFile:33) ~[?:?]
	at dev.lone.itemsadder.f.a.<init>(SourceFile:50) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:226) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:86) ~[patched_1.15.2.jar:git-Paper-161]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-161]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`
	
THe plugin mentiones that it's a hint for the plugin dev so it might be interesting for you :D

And now some suggestions:

Perhaps you can add a "little debuff" as behaviour to food where we can define that a player got a bit more thirst loss over time after eating something what would make more thirst in real life,

The other thing is we are running a BungeeCord network and have 2 severs. At the moment we can't syncronize the thirst and the manabar. I saw that you were saying you want to make a better API for devs so perhaps you can add 
something like itemsadder.setthirst(Player p, int thist) and Itemsadder.getthirst(Player p), and the same for mana.

Yes I know it's quite a lot and of course it's clear that you don't have to add it all quickly, but I thought it'd be better to write it down somewhere before some things slip my mind. ^^

thank you in advance

- D3nied

**Comment by LoneDev6** [comment]
> Hey, fist of all thx for fixing the OnJoinBug

no problem!

> The first question is bread and other normal vanilla foods fill up water. Is there a way to change the amount
because I didn't find anything. There#s a chance that I skipped it tho.

what do you mean?

> So the other thing with thirst is that it seems that the plugin doesn't recognize the nether as biome:

Please set min_sky_light to 0, Nether biome has light 0

> The other thing is a info from a plugin called LagMonitor

ignore it, it's initialization of itemsadder :) don't worry. I'll try to optimize it but i don't think i can. it takes just 1 second


> more thirst loss over time after eating something what would make more thirst in real life,

that is interesting, I have to think about how to implement this as the plugin is structured in a way that doesn't allow that specific behaviour

> something like itemsadder.setthirst(Player p, int thist) and Itemsadder.getthirst(Player p), and the same for mana.

for now you can use this command: 
/iaplayerstat write LoneDev mana float 5
/iaplayerstat write LoneDev thirst float 10


> Yes I know it's quite a lot and of course it's clear that you don't have to add it all quickly, but I thought it'd be better to write it down somewhere before some things slip my mind. ^^

no problem! ;) i'll try my best





NOTE: Please, if some of these questions I answered are still unrestolved open a github "feature request" for each of these, so I can manage it better.
Thanks!
