### ISSUE TITLE
itemsadder crops bug

### ISSUE THREAD

**Issue by ninesik** [LoneDev6/ItemsAdder#166]
If you collect custom crops with items attached to the fortune, an error will appear in the bucket.

[09:11:45 ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.0.9
java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.EntityItem.setItemStack(EntityItem.java:433) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.EntityItem.<init>(EntityItem.java:42) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItem(CraftWorld.java:712) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.dropItemNaturally(CraftWorld.java:729) ~[patched_1.15.2.jar:git-Paper-201]
        at dev.lone.itemsadder.d.c.k.a(SourceFile:48) ~[?:?]
        at dev.lone.itemsadder.d.d.a.b.g.b(SourceFile:88) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-201]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-201]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:315) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:274) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:215) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1324) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1144) ~[patched_1.15.2.jar:git-Paper-201]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-201]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by ninesik** [comment]
https://youtu.be/EyHqXUZz_Mw

**Comment by LoneDev6** [comment]
Hello!
Let me know if it's fixed in new plugin, please remember to always update, you're on old version.

If it's not fixel please reopen this issue.
