### ISSUE TITLE
[BUG] Server stucks when player join before ItemsAdder load completed

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#168]
**Describe the bug**
When the player join the server before the loading of the ItemsAdder is completed, the server will stucks.

**To Reproduce**
1. Start server program
2. Some player join server when server still install
3. Server main thread blocking, and ItemsAdder loop print exceptions

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia
 - Plugin version: 2.0.13

**Additional context**
here is a part of my log:
```
[22:40:55] [Server thread/INFO]: - Extracting default items from .jar
[22:40:55] [Server thread/INFO]:   - DONE extracting default items from .jar
[22:40:55] [Server thread/INFO]: Used 558/6608 available max font images. 
[22:40:56] [Server thread/INFO]: Loaded 502 items
[22:40:56] [Server thread/INFO]: Used 27/191 REAL block IDs. 
[22:40:56] [Server thread/WARN]: [ItemsAdder] Task #53 for ItemsAdder v2.0.13 generated an exception
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.b(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.c(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.f(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.d.b.g(SourceFile:922) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:86) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:40:57] [Craft Scheduler Thread - 15/INFO]: [Brewery] Background data loading complete.
[22:40:57] [Server thread/INFO]: - Extracting default items from .jar
[22:40:57] [Server thread/INFO]:   - DONE extracting default items from .jar
[22:40:57] [Server thread/INFO]: Used 558/6608 available max font images. 
[22:40:58] [Server thread/INFO]: Loaded 502 items
[22:40:58] [Server thread/INFO]: Used 27/191 REAL block IDs. 
[22:40:58] [Server thread/WARN]: [ItemsAdder] Task #53 for ItemsAdder v2.0.13 generated an exception
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.b(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.c(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.f(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.d.b.g(SourceFile:922) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:86) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[22:40:58] [Server thread/INFO]: - Extracting default items from .jar
[22:40:58] [Server thread/INFO]:   - DONE extracting default items from .jar
[22:40:59] [Server thread/INFO]: Used 558/6608 available max font images. 
[22:41:00] [User Authenticator #1/INFO]: UUID of player SnowRaon is 2791dfdd-f2bf-444a-a786-2c830f814ed9
[22:41:00] [Server thread/INFO]: Loaded 502 items
[22:41:00] [Server thread/INFO]: Used 27/191 REAL block IDs. 
[22:41:00] [Server thread/WARN]: [ItemsAdder] Task #53 for ItemsAdder v2.0.13 generated an exception
java.lang.NullPointerException: null
	at dev.lone.itemsadder.d.e.b(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.c(SourceFile:86) ~[?:?]
	at dev.lone.itemsadder.d.b.b.b.f(SourceFile:67) ~[?:?]
	at dev.lone.itemsadder.d.b.g(SourceFile:922) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:224) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:86) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1203) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1121) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:940) ~[patched_1.15.2.jar:git-Tuinity-"0729373"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
there was more same error like this in log.

**Comment by R-Josef** [comment]
To solve this problem, I have to turn on whitelist when server install and off white list when itemsadder complete. I think it will be better if let player can only join when itemsadder was all completed.

**Comment by LoneDev6** [comment]
Hello,
please can you send me your complete log?
I suspect this issue is generated from another issue, this log is only partial.
You can publish it on pastebin or dropbox, or other website.

Thanks

**Comment by R-Josef** [comment]
Yes, of course.

**Comment by R-Josef** [comment]
[complete log](https://pastebin.com/krAqm9BD)

**Comment by R-Josef** [comment]
Sorry i close this issue by mistake.

**Comment by LoneDev6** [comment]
I read error "Resource pack hash cannot be null", probably resourcepack url has something strange.

Send me the config.yml file

**Comment by R-Josef** [comment]
ok, here is:
```yaml
metrics: true
resource-pack:
  apply-on-join: true
  kick-player-on-decline: true
  kick-player-on-fail: false
  delay-ticks: 1
  self-host:
    enabled: false
    server-ip: server.yinwurealm.org
    pack-port: 8163
  external-host:
    enabled: true
    url: http://fengshuai.oss-cn-shenzhen.aliyuncs.com/mcserver/CT_V38_7.zip
  custom-font:
    enabled: false
    name: ipaexg.ttf
blocks:
  light-api: true
  fix-bugged-mushrooms:
    enabled: true
    only-new-chunks: true
  cancel-break-wrong-tool:
    enabled: true
    send-actionbar: true
    mining-fatigue:
      enabled: true
      duration: 20
      amplifier: 1
  campfire:
    unlit-on-place: true
    allow-any-item: true
items:
  fix-show-attack-and-damage-as-lore: true
  give_death_location_maps: true
font_images:
  negative-spaces-font:
    enabled: true
  chat:
    enabled: true
  command:
    enabled: true
    commandblocks: true
    excluded:
    - home
    - sethome
    - tpa
  sign:
    enabled: true
  book:
    enabled: true
  anvil:
    enabled: true
huds:
  enabled: true
config_files:
  update-automatically: false
  lang: zh
  extract-default-items: true
  extract-default-resources: true
debug:
  items:
    log-files-loading: false
    log-items-loading: false
    log-font-images-loading: false
    log-huds-loading: false
    log-attribute-modifiers-loading: false
    log-warnings: false
    log-loots-loading: false
  recipes:
    log-recipes-loading: false
  resource-pack:
    log-extract-default-resources: false
    log-not-extract-default-resources-already-exist: false
  blocks:
    log-save: true
    log-save-on-unload: false
    log-mined-unknown-blocks: true
  worlds-populators:
    log-loading: false
    log-loading-no-populators: false
    log-generation: false
  player-stats:
    log-save: true
  performance:
    loading-ms: true
  huds:
    log-triggers: false

```

**Comment by LoneDev6** [comment]
Can you tell me if this problem also happens on 2.0.14?
(The loop problem, where the plugin keeps loading infinitely)

I already released the update, please let me know.
Thanks!

**Comment by R-Josef** [comment]
No, this is not happen anymore, thank you!

**Comment by LoneDev6** [comment]
Perfect! :D No problem
