### ISSUE TITLE
[BUG] Exception when loading custom language file.

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#169]
**Describe the bug**
Exception when loading custom language file.

**To Reproduce**
1. Custom a language file (I use Chinese)
2. Install server
3. See error

**Info (please complete the following information):**
 - Server version: tuinity 1.15.2
 - Client version: vanllia 1.15.2
 - Plugin version: 2.0.13

**Additional context**
Here is a part of log about this problem:
```
[22:40:33] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.0.13
[22:40:33] [Server thread/INFO]: ------ ItemsAdder ------
[22:40:33] [Server thread/INFO]:   _____ _                                 _     _           
[22:40:33] [Server thread/INFO]:  |_   _| |                       /\      | |   | |          
[22:40:33] [Server thread/INFO]:    | | | |_ ___ _ __ ___  ___   /  \   __| | __| | ___ _ __ 
[22:40:33] [Server thread/INFO]:    | | | __/ _ \ '_ ` _ \/ __| / /\ \ / _` |/ _` |/ _ \ '__|
[22:40:33] [Server thread/INFO]:   _| |_| ||  __/ | | | | \__ \/ ____ \ (_| | (_| |  __/ |   
[22:40:33] [Server thread/INFO]:  |_____|\__\___|_| |_| |_|___/_/    \_\__,_|\__,_|\___|_|   
[22:40:33] [Server thread/INFO]:                                                             
[22:40:33] [Server thread/INFO]:                                                             
[22:40:33] [Server thread/INFO]: Loading data...
[22:40:33] [Server thread/WARN]: java.lang.NullPointerException
[22:40:33] [Server thread/WARN]: 	at java.base/java.io.Reader.<init>(Reader.java:167)
[22:40:33] [Server thread/WARN]: 	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:97)
[22:40:33] [Server thread/WARN]: 	at dev.lone.itemsadder.j.d.ai(SourceFile:102)
[22:40:33] [Server thread/WARN]: 	at dev.lone.itemsadder.j.d.<init>(SourceFile:64)
[22:40:33] [Server thread/WARN]: 	at dev.lone.itemsadder.Main.onEnable(SourceFile:62)
[22:40:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:40:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[22:40:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[22:40:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[22:40:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[22:40:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:487)
[22:40:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299)
[22:40:33] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:890)
[22:40:33] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[22:40:33] [Server thread/INFO]: ERROR LOADING file 'plugins/ItemsAdder/lang/zh.yml'
```
Here is my language file:
```yaml
attribute-armor: '&9+{value} 盔甲'
attribute-toughness: '&9+{value} 盔甲韧性'
attribute-attack-damage: '&2{value} 攻击伤害'
attribute-attack-speed: '&2{value} 攻击速度'
attribute-when-in-main-hand: '&7在主手时:'
attribute-when-on-body: '&7穿在身上时:'
attribute-when-on-feet: '&7穿在腿上时:'
attribute-when-on-head: '&7戴在头上时:'
attribute-when-on-legs: '&7穿在脚上时:'
cannot-break-with-this-tool: '&c你不能用此工具破坏它'
cannot-repair: '&c无法修复这件物品'
repaired-successfully: '&a成功修复物品!'
cannot-set-durability: '&c无法设置耐久度!'
set-durability-successfully: '&a成功设置耐久度!'
crafting-no-recipe: '&e这件物品没有合成配方'
given-item: '&a已给予&e{player}&a物品&e{item} '
item-not-found: '&c物品&3{item}&c不存在'
items-count: '&b物品数: &a{count}'
lore-usages: '&7用法: {value}'
lore-durability: '&7耐久度: {value} / {max}'
model-id: '&b模型ID: {value}'
name-config: '&b配置内的名称: '
no-craft-permission: '&e你没有合成这件物品的权限!'
no-permission: '&c你没有使用这个指令的权限!'
no-permission-detail: '&c你没有使用这个指令的权限! &e{permission}'
no-permission-short: '&cNo permission'
now-playing: '&f正在播放: {value}'
obtained-item: '&a已获得物品 &e{item}'
player-full-inventory: '&c玩家背包已满!'
player-offline: '&e玩家不在线'
prefix: '[ItemsAdder] '
resourcepack-error: '&4启用资源包时出错. 请联系管理员!'
resourcepack-kick-declined: '&4请使用服务器的资源包! 同时确认管理员在服务器配置内开启了服务器资源包.'
wrong-command-usage: '&c指令用法错误'
emoji-gui-title: '&3&l表情符号列表'
map-death-location: 死亡坐标
fuel-indicator: '&b&l燃料: {value}/{max}'
drop-from-block: '&f从方块中掉落'
drop-from-mob: '&f由怪物掉落'
drop-from-fishing: '&f钓鱼获得'
get-from-trade-machine: '&f从交易机中获得'
ore-info: '&f矿物生成信息'
worlds: '&b世界:'
info: '&b信息:'
chance: '&f   几率: &7{value}%'
amount: '&f   数量: &7{value}'
min-height: '&f   最小高度: &7{value}'
max-height: '&f   最大高度: &7{value}'
drops-itself: '&e   掉落其本身'
vehicle-fuel-items: '&e燃料物品'
fuel-item: '    &b{type} &7+{amount}'
iarecipe-wrong-usage: '&c指令用法错误. 正确用法: &e/iarecipe <item name>&c, &a或将物品拿在手中'
iarecipe-no-custom-item: '&c这不是自定义项目! 请手持自定义物品&a或使用指令: &e/iarecipe <item name>'
anvil-repair-info: '&f铁砧修复材料'
ia-title-menu-categories: '&3&l物品目录'
ia-title-recipe-view: '&3&l制造图'
ia-button-search: '&f搜索...'
ia-button-back: '&f返回'
ia-button-next-page: '&f下一页->'
ia-button-previous-page: '&f<-上一页'
ia-button-next-recipe: '&f下一个请求'
ia-button-previous-recipe: '&f上一个请求'
ia-search-results: '&f搜索结果'
ia-smeling: '&f冶炼'
ia-smelting: '&f编辑物品'
ia-button-get-item: '&f获得物品'
ia-vanilla-type: '&f原版类型'
ia-model-id: '&f模组ID'
ia-title-crafting-view: '&f主菜单'
player-stat-value-read: '&e数值: &b{value}'
player-stat-value-write: '&e数值已更改!'
ia-button-loot-blocks: '&f从方块中掉落'
ia-button-loot-mobs: '&f由怪物掉落'
ia-button-loot-fishing: '&f钓鱼获得'
ia-button-vehicle-fuel-items: '&e燃料物品'
nbt-rule: '&f   {rule}: &7{value}'
resourcepack-not-ready: '&6资源包准备失败. 几秒钟后将会自动启用...'

```
I have checked, I think this config conforms to yaml syntax, it also contains all the keys of the latest english language file.

**Comment by R-Josef** [comment]
And it looks everything is ok, the language file can be used, but the error message print every server start.

**Comment by LoneDev6** [comment]
Thanks!
This will be fixed in next update
