### ISSUE TITLE
[BUG] console error

### ISSUE THREAD

**Issue by ninesik** [LoneDev6/ItemsAdder#196]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: (example: paper 1.15.2)
 - Client version: (example: fabric 1.15.2)
 - Plugin version: (example: 2.0.9 do not write "latest")

**Additional context**

[18:27:29 ERROR]: Could not pass event EntityDeathEvent to ItemsAdder v2.0.15
java.lang.NullPointerException: Entity can't be null/dead!
        at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTEntity.<init>(SourceFile:28) ~[?:?]
        at dev.lone.itemsadder.d.e.a.g.a(SourceFile:72) ~[?:?]
        at dev.lone.itemsadder.d.e.a.a(SourceFile:260) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-226]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityVillagerAbstract.die(EntityVillagerAbstract.java:192) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityVillager.die(EntityVillager.java:541) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1113) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1706) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2062) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1148) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by LoneDev6** [comment]
Thanks, reopen this issue if it's not fixed in next update
