### ISSUE TITLE
[BUG] can't use Itemsadder v.2.0.16

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#197]
**Describe the bug**

**To Reproduce**
1. download Itemsadder v.2.0.16
2. put into plugins
3. start server

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50344708/80706579-1b806a80-8b1b-11ea-96c2-b5284beef4c8.png)

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2 with WWE
 - Plugin version: 2.0.16

**Additional context**
[19:30:11] [Server thread/INFO]: [0;36;1m- Extracting default items from .jar[m
[19:30:11] [Server thread/INFO]: [0;32;1m  - DONE extracting default items from .jar[m
[19:30:11] [pool-67-thread-1/INFO]: [0;34;1m[[0;36;1m TPS Meter [0;34;1m][0;33;1m The server's TPS is bellow [0;31;1m2.0[0;33;1m, is it lagging or crashed?[m
[19:30:13] [Server thread/INFO]: [0;33;1mUsed [0;36;1m558[0;33;1m/[0;36;1m6608[0;33;1m available max font images. [m
[19:30:14] [Server thread/WARN]: [ItemsAdder] Task #938 for ItemsAdder v2.0.16 generated an exception
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap
	at dev.lone.itemsadder.j.a.c.ak(SourceFile:16) ~[?:?]
	at dev.lone.itemsadder.d.g.c.c.a(SourceFile:65) ~[?:?]
	at dev.lone.itemsadder.d.b.g(SourceFile:762) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:228) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[19:30:14] [Server thread/INFO]: [0;36;1m- Extracting default items from .jar[m
[19:30:14] [Server thread/INFO]: [0;32;1m  - DONE extracting default items from .jar[m
[19:30:16] [Server thread/INFO]: [0;33;1mUsed [0;36;1m558[0;33;1m/[0;36;1m6608[0;33;1m available max font images. [m
[19:30:18] [Server thread/WARN]: [ItemsAdder] Task #938 for ItemsAdder v2.0.16 generated an exception
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2ObjectLinkedOpenHashMap
	at dev.lone.itemsadder.j.a.c.ak(SourceFile:16) ~[?:?]
	at dev.lone.itemsadder.d.g.c.c.a(SourceFile:65) ~[?:?]
	at dev.lone.itemsadder.d.b.g(SourceFile:762) ~[?:?]
	at dev.lone.itemsadder.d.b.a(SourceFile:228) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Command1264** [comment]
Itmesadder V.2.0.15 can use

**Comment by LoneDev6** [comment]
Thanks, please update and let me know.
reopen this issue if the issue will not be fixed after updating
