### ISSUE TITLE
NullPointer

### ISSUE THREAD

**Issue by D3nied** [LoneDev6/ItemsAdder#205]
**Describe the bug**
Nullpointer when placing a normal mushroom block on fence/wall

**To Reproduce**
1. Go to your creative inventory
2. get a Mushroom block brown/red
3. place it on a cobblestone wall
`[04:12:31 ERROR]: Could not pass event BlockPlaceEvent to ItemsAdder v2.0.18
java.lang.IllegalArgumentException: Cannot set property null as it does not exist in Block{minecraft:cobblestone_wall}
        at net.minecraft.server.v1_15_R1.BlockDataAbstract.set(BlockDataAbstract.java:102) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_15_R1.block.data.CraftBlockData.set(CraftBlockData.java:239) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_15_R1.block.impl.CraftCobbleWall.setFace(CraftCobbleWall.java:29) ~[patched_1.15.2.jar:git-Paper-245]
        at dev.lone.itemsadder.d.d.a.b.b.b.a(SourceFile:413) ~[?:?]
        at dev.lone.itemsadder.d.d.a.b.b.b.c(SourceFile:195) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-245]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:345) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:236) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:508) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1407) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035) ~[patched_1.15.2.jar:git-Paper-245]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950) ~[patched_1.15.2.jar:git-Paper-245]
        at java.lang.Thread.run(Unknown Source) [?:?]`

**Info (please complete the following information):**
 - Server version: paper 1.15.2 (245)
 - Client version: Optifine
 - Plugin version: 2.0.18

**Additional context**
Well im not sure if this is relevant but when a user join i get thirst_bar-21.0 printed in the console i guess this is some kind of debug message ?

**Comment by LoneDev6** [comment]
fixed in next update, thanks
