### ISSUE TITLE
[BUG] Could not pass event EntityDeathEvent to RPGMoney v1.1.20

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#220]
`[14:15:19]: [ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.1.20
java.lang.IllegalArgumentException: No enum constant com.evill4mer.RealMoney.XMaterial.coin
at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
at com.evill4mer.RealMoney.XMaterial.valueOf(SourceFile:31) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.a(SourceFile:575) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.b(SourceFile:588) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.a(SourceFile:607) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.b(SourceFile:523) ~[?:?]
at com.evill4mer.RealMoney.c.b.a(SourceFile:221) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor941.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-226]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:457) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:225) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:419) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityZombie.tick(EntityZombie.java:180) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.World.a(World.java:869) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]
[14:15:24]: [INFO] Fargus issued server command: /iatexture
[14:15:25]: [ERROR] Could not pass event EntityDeathEvent to RPGMoney v1.1.20
java.lang.IllegalArgumentException: No enum constant com.evill4mer.RealMoney.XMaterial.coin
at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
at com.evill4mer.RealMoney.XMaterial.valueOf(SourceFile:31) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.a(SourceFile:575) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.b(SourceFile:588) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.a(SourceFile:607) ~[?:?]
at com.evill4mer.RealMoney.RealMoney.b(SourceFile:523) ~[?:?]
at com.evill4mer.RealMoney.c.b.a(SourceFile:221) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor941.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-226]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.Entity.entityBaseTick(Entity.java:457) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:244) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:225) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:419) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityInsentient.tick(EntityInsentient.java:288) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.World.a(World.java:869) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by LoneDev6** [comment]
apri il config.yml di RPGMoney e impostalo così:
https://itemsadder.plugin.ga/compatibility-with-other-plugins/compatible/rpgmoney
