### ISSUE TITLE
[BUG]  Could not pass event EntityDeathEvent to ItemsAdder v2.0.22

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#221]
[14:35:19]: [ERROR] Could not pass event EntityDeathEvent to ItemsAdder v2.0.22
java.lang.NullPointerException: null
at dev.lone.itemsadder.d.e.a.a(SourceFile:271) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-226]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:759) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.damage(CraftLivingEntity.java:311) ~[patched_1.15.2.jar:git-Paper-226]
at org.mcmonkey.sentinel.SentinelWeaponHelper.punch(SentinelWeaponHelper.java:252) ~[?:?]
at org.mcmonkey.sentinel.SentinelAttackHelper.tryAttackInternal(SentinelAttackHelper.java:323) ~[?:?]
at org.mcmonkey.sentinel.SentinelAttackHelper.tryAttack(SentinelAttackHelper.java:104) ~[?:?]
at org.mcmonkey.sentinel.SentinelTrait.runUpdate(SentinelTrait.java:1299) ~[?:?]
at org.mcmonkey.sentinel.SentinelTrait.run(SentinelTrait.java:1504) ~[?:?]
at net.citizensnpcs.api.npc.AbstractNPC.update(AbstractNPC.java:435) ~[?:?]
at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:323) ~[?:?]
at net.citizensnpcs.nms.v1_15_R1.entity.EntityHumanNPC.tick(EntityHumanNPC.java:425) ~[?:?]
at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.World.a(World.java:869) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LoneDev6** [comment]
Non ho idea della causa di questo bug, però noto che nell'errore è citato anche il plugin "org.mcmonkey.sentinel", ti consiglio di inviare questo errore anche al dev del plugin
