### ISSUE TITLE
[BUG] Plugin ItemsAdder v2.0.22 generated an exception while executing task 2586

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#222]
[15:07:34]: [WARN] [ItemsAdder] Plugin ItemsAdder v2.0.22 generated an exception while executing task 2586
java.lang.IllegalArgumentException: Resource pack hash cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setResourcePack(CraftPlayer.java:1471) ~[patched_1.15.2.jar:git-Paper-226]
at dev.lone.itemsadder.h.c.b(SourceFile:511) ~[?:?]
at dev.lone.itemsadder.h.c.s(SourceFile:497) ~[?:?]
at dev.lone.itemsadder.h.a.r(SourceFile:68) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LoneDev6** [comment]
Evita di cancellare il template del report, altrimenti non ha senso che l'abbia creato, mi serve per evitare di perdere tempo a farti queste domande e poter correggere subito:

- Hai idea di quando venga generato questo errore?
- Fai qualche azione specifica?

> **Describe the bug**
A clear and concise description of what the bug is.
> 
> **To Reproduce**
Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Info (please complete the following information):**
>  - Server version: (example: paper 1.15.2)
>  - Client version: (example: fabric 1.15.2)
>  - Plugin version: (example: 2.0.9 do not write "latest")
> 
> **Additional context**
> Add any other context about the problem here.

**Comment by pingarss** [comment]
I have the same issue after executing /iazip, it started to happen like 30 minutes ago.

Error:
[ItemsAdder] Plugin ItemsAdder v3.6.3-beta-13 generated an exception while executing task 17091
java.lang.ArithmeticException: / by zero
        at ia.m.qm.b(SourceFile:234) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qm.a(SourceFile:218) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qm.g(SourceFile:210) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qo.a(SourceFile:283) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qo.cO(SourceFile:105) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.qe.cE(SourceFile:676) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.G.a(SourceFile:1202) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.iu.a(SourceFile:84) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at ia.m.G.a(SourceFile:975) ~[ItemsAdder_3.6.3-beta-13.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-462]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-462]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
