### ISSUE TITLE
[BUG] Builder's Basic Addon

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#223]
I have installed the addon, but this is what I have:

![image](https://user-images.githubusercontent.com/20026629/81700622-303cf680-9469-11ea-899b-cffd375407da.png)

**Comment by Fargus5** [comment]
`[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:black removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:orange removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:stone removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:turquoise removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:strange removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:wood removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:jack_o_lantern removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:brown removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:ender removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:green removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:spider removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:cave_spider removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:bones removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:pink removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:purple removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:minerals removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:dark_jack_o_lantern removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:blue removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:grocery_bag removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:redstone removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:red removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:chest removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:yellow removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:black removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:orange removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:stone removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:turquoise removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:strange removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:wood removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:jack_o_lantern removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:brown removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:ender removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:green removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:spider removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:cave_spider removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:bones removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:pink removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:purple removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:minerals removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:dark_jack_o_lantern removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:blue removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:grocery_bag removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:redstone removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:red removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:chest removed now.
[16:00:27]: [ERROR] Tried to load unrecognized recipe: epicbackpacks:yellow removed now.
[16:00:27]: [WARN] [VoxelSniper] Loaded class com.sk89q.worldedit.extension.platform.Actor from WorldEdit v1.15-184;058990f which is not a depend, softdepend or loadbefore of this plugin.
[16:00:27]: [INFO] try to load furniture in world: worldtry to load furniture in world: world_nethertry to load furniture in world: world_the_endtry to load furniture in world: Modern[ReflectionHelper] I am loaded from package org.inventivetalent.glow.reflection.minecraft
[16:00:27]: [INFO] [ReflectionHelper] Version is v1_15_R1 (11501)
[16:00:28]: [INFO] Sebastiano17[/185.172.206.2:52779] logged in with entity id 1696 at ([world]-14242.892644211204, 54.136152970330606, -3221.699999988079)
[16:00:28]: [WARN] [ItemsAdder] Plugin ItemsAdder v2.0.22 generated an exception while executing task 313
java.lang.IllegalArgumentException: Resource pack hash cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.setResourcePack(CraftPlayer.java:1471) ~[patched_1.15.2.jar:git-Paper-226]
at dev.lone.itemsadder.h.c.b(SourceFile:511) ~[?:?]
at dev.lone.itemsadder.h.c.s(SourceFile:497) ~[?:?]
at dev.lone.itemsadder.h.a.r(SourceFile:68) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[16:00:29]: [INFO] [ItemsAdder] Found cached default resourcepack
[16:00:29]: [INFO] Extracting resources from default resourcepack
[16:00:29]: [INFO] DONE extracting resources from default resourcepack
[16:00:29]: [WARN] Can't keep up! Is the server overloaded? Running 5983ms or 119 ticks behind`

**Comment by LoneDev6** [comment]
- Stai usando l'ultima versione di ItemsAdder?
- Hai usato il comando /iatexture sul tuo gioco per ricaricare la texture di Minecraft?

L'errore " Tried to load unrecognized recipe" puoi ignorarlo, capita se uno dei plugin è stato rimosso e reinstallato mentre un utente che aveva già imparato le ricette del plugin entra nel server.
Non è un errore grave, ma solo un avviso che puoi ignorare tranquillamente.


Fammi sapere

**Comment by LoneDev6** [comment]
è strano, facendo il procedimento:

- server: /iareload
- server: /iazip
- gioco: /iatexture

dovrebbe andare senza dover riavviare tutto



> Io ho rifatto un riavvio del server ora e questa lista di errori non me la da più. Che sia stato solo una lista di errori che si mostrava solo la prima volta?

sì viene mostrato una volta per ogni giocatore che conosceva le ricette quando accendi il server senza il plugin delle ricette installato (in quel caso epicbackpacks) , d'ora in poi non dovresti vederlo più

**Comment by Fargus5** [comment]
D'accord, grazie mille per tutto quello che fai per noi.

**Comment by LoneDev6** [comment]
Di nulla, provo sempre a rispondere a tutti quanti e a sviluppare gli aggiornamenti ;)
