### ISSUE TITLE
[BUG] - NBT bug

### ISSUE THREAD

**Issue by ICEconchy** [LoneDev6/ItemsAdder#231]
**Describe the bug**
On server boot the plugin errors and disables

**To Reproduce**
I do not know how to reproduce this as I have not edited the plugin since our last correspondence

**Expected behavior**
For it to work

**Screenshots**
`[21:57:02] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.0.20
[21:57:02] [Server thread/INFO]: ------ ItemsAdder ------
[21:57:02] [Server thread/INFO]:   _____ _                                 _     _           
[21:57:02] [Server thread/INFO]:  |_   _| |                       /\      | |   | |          
[21:57:02] [Server thread/INFO]:    | | | |_ ___ _ __ ___  ___   /  \   __| | __| | ___ _ __ 
[21:57:02] [Server thread/INFO]:    | | | __/ _ \ '_ ` _ \/ __| / /\ \ / _` |/ _` |/ _ \ '__|
[21:57:02] [Server thread/INFO]:   _| |_| ||  __/ | | | | \__ \/ ____ \ (_| | (_| |  __/ |   
[21:57:02] [Server thread/INFO]:  |_____|\__\___|_| |_| |_|___/_/    \_\__,_|\__,_|\___|_|   
[21:57:02] [Server thread/INFO]:                                                             
[21:57:02] [Server thread/INFO]:                                                             
[21:57:02] [Server thread/INFO]: Failed to get username for: 57082
[21:57:02] [Server thread/INFO]: Loading data...
[21:57:02] [Server thread/INFO]: Found resourcepack folder: /home/minecraft/multicraft/servers/server119653/plugins/ItemsAdder/data/resource_pack
[21:57:02] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.0.20 (Is it up to date?)
dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:59) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTFile.<init>(SourceFile:36) ~[?:?]
	at dev.lone.itemsadder.d.d.a.b.b.b.<init>(SourceFile:58) ~[?:?]
	at dev.lone.itemsadder.d.b.f(SourceFile:196) ~[?:?]
	at dev.lone.itemsadder.d.b.<init>(SourceFile:153) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:153) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_242]
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_242]
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_242]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_242]
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_242]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:18) ~[patched_1.15.2.jar:git-Paper-282]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
[21:57:02] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.0.20
[21:57:02] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[21:57:02] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v2.0.20 (Is it up to date?)
java.lang.NullPointerException: null
	at dev.lone.itemsadder.Main.onDisable(SourceFile:163) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-282]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-282]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: Vanilla 1.15.2
 - Plugin version: v2.0.20

**Comment by ICEconchy** [comment]
https://mcpaste.io/a010126a3ceddae1

As I didn't know the code tag wouldn't work, heres a paste.

**Comment by D3nied** [comment]
in my opinion its a corruptet nbt file you can try to go to the storage\regions_data\<yourworldname> and delete all the files or you can try to use a programm like NBTEditor and try to open the files the one that can't be opend is the corrupted file

**Comment by LoneDev6** [comment]
Hello, did the server crash or did you killed it? Probably it got interrupted while saving an NBT file.
I doubt it's a region file because corrupted region files don't cause crashes anymore as they get simply deleted and regenerated when they got corrupted.

The only NBT file that is not checked for corruption is this one, delete it and restart:
plugins\ItemsAdder\storage\cache\various\fixed_mushrooms_chunks.nbt


avoid deleting the regions_data folder because it's not the cause of the corruption and would cause all your custom blocks in world to become mushrooms.

let me know

**Comment by ICEconchy** [comment]
I've found out that my host, shockbyte, ran out of space. Causing corruption. Even though they said it was unlimited. This also caused other problems on my server.

**Comment by LoneDev6** [comment]
Damn, that's a shame.
I'm sorry for the inconvenience.
