### ISSUE TITLE
[BUG] Internal Error when HUDs is disabled

### ISSUE THREAD

**Issue by deadfish12** [LoneDev6/ItemsAdder#235]
**Describe the bug**
Whenever I change huds enabled to "false" in config.yml, I can't reload the plugin using /iareload and will receive error messages. With all other settings remain exactly the same, there won't be any internal error when reloading if huds enabled is "true".
All data are default (items_packs and resource_packs), only config.yml is changed.

**To Reproduce**
1. Go to 'config.yml' and change "huds: enabled:" to "false"
2. Restart the server to apply the above change
3. Reload the plugin in-game with /iareload
4. See error in-game and in console

**Expected behavior**
Changing to false should disable HUDs and able to reload the plugin normally without any error.

**Screenshots**
![image](https://user-images.githubusercontent.com/61008844/82086128-9dc67c80-9720-11ea-85ea-a57bd52c89d8.png)
```
[02:45:58 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iareload' in plugin ItemsAdder v2.0.22
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-261]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-261]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1852) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1160) ~[patched_1.15.2.jar:git-Paper-261]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:958) ~[patched_1.15.2.jar:git-Paper-261]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
at dev.lone.itemsadder.d.b.b.b.s(SourceFile:192) ~[?:?]
at dev.lone.itemsadder.c.k.onCommand(SourceFile:34) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-261]
... 17 more
```

**Info (please complete the following information):**
 - Server version: paper 1.15.2 (build #284)
 - Client version: 1.15.2
 - Plugin version: 2.0.22

**Comment by deadfish12** [comment]
After further testing, the problem seems to be in the thirst_bar under realcraft. 
If I enable HUDs in config, but remove huds.yml in realcraft or only delete the content in the file, the same error occurs.
Removing the magiccraft folder will not cause the error.

**Comment by LoneDev6** [comment]
Fixed in the new update, thanks!
I will publish it later, reopen this if you will still have problems
