### ISSUE TITLE
[BUG] strange bug, don't know why

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#238]
**Describe the bug**
`[16:42:27]: [INFO] Fargus issued server command: /iareload
[16:42:27]: [INFO] Found resourcepack folder: /home/gameserver/servers/serveur6/minecraft/plugins/ItemsAdder/data/resource_pack
[16:42:27]: [INFO] [ItemsAdder] Resourcepack initialization...
[16:42:27]: [INFO] [ItemsAdder] Checking for online default resourcepack updates...
[16:42:27]: [INFO] [ItemsAdder] All worlds: saved 0 regions
[16:42:27]: [INFO] [ItemsAdder] Saved 3 player stats files
[16:42:27]: [INFO] [ItemsAdder] Found cached default resourcepack
[16:42:27]: [INFO] Extracting resources from default resourcepack
[16:42:27]: [INFO] DONE extracting resources from default resourcepack
[16:42:27]: [INFO] - Extracting default items from .jar
[16:42:27]: [INFO] - DONE extracting default items from .jar
[16:42:27]: [INFO] Used 558/13216 available max font images.
[16:42:27]: [INFO] [EpicBackpacks] ItemsAdder finished loading, now loading backpacks...
[16:42:27]: [INFO] [EpicBackpacks] Loaded backpacks correctly
[16:42:27]: [ERROR] Could not pass event FoodLevelChangeEvent to ItemsAdder v2.0.22
java.lang.NullPointerException: null
at dev.lone.itemsadder.d.e.a(SourceFile:107) ~[?:?]
at dev.lone.itemsadder.d.b.a.a.a.a.a(SourceFile:45) ~[?:?]
at dev.lone.itemsadder.d.b.b.b.a(SourceFile:320) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-226]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:1126) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:1121) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.FoodMetaData.a(FoodMetaData.java:54) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityHuman.tick(EntityHuman.java:177) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.EntityPlayer.playerTick(EntityPlayer.java:442) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.PlayerConnection.tick(PlayerConnection.java:150) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1328) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]
[16:42:28]: [INFO] Loaded 574 items
[16:42:28]: [INFO] Used 117/191 REAL block IDs.
[16:42:28]: [INFO] [ItemsAdder] Checking resourcepack url... http://www.survivalla.fun/respack/pack10.zip
[16:42:28]: [WARN] [ItemsAdder] Task #395365 for ItemsAdder v2.0.22 generated an exception
java.lang.NullPointerException: null
at dev.lone.itemsadder.d.e.a(SourceFile:107) ~[?:?]
at dev.lone.itemsadder.d.b.a.a.b.a.a(SourceFile:52) ~[?:?]
at dev.lone.itemsadder.d.b.a.f.b(SourceFile:66) ~[?:?]
at dev.lone.itemsadder.d.b.b.b.w(SourceFile:152) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]
[16:42:28]: [WARN] [ItemsAdder] Plugin ItemsAdder v2.0.22 generated an exception while executing task 395364
java.lang.NullPointerException: null
at dev.lone.itemsadder.d.e.a(SourceFile:107) ~[?:?]
at dev.lone.itemsadder.d.b.a.f.a(SourceFile:129) ~[?:?]
at dev.lone.itemsadder.d.b.b.b.y(SourceFile:139) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-226]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-226]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
[16:42:28]: [INFO] [ItemsAdder] Resourcepack URL is valid. Type: application/zip
[16:42:30]: [INFO] Loaded 41 categories (ia_gui.yml)
[16:42:30]: [INFO] [ItemsAdder] Loaded items and stuff in 3478ms`

**To Reproduce**
1. I changed the durability of swords and I did /iareload
Ha funzionato, però è apparso questo errore in console. non so da che cosa sia dovuto

**Comment by Fargus5** [comment]
Ho rifatto di nuovo e stavolta non è apparso l'errore.

**Comment by LoneDev6** [comment]
Ciao, dovrebbe essere corretto nel prossimo update
