### ISSUE TITLE
[BUG] null error

### ISSUE THREAD

**Issue by Command1264** [LoneDev6/ItemsAdder#242]
**Describe the bug**
null error

**To Reproduce**
1. open server
2. Enter command "/iareload"
3. See error

**Expected behavior**
reload item and config(?)

**Screenshots**
![image](https://user-images.githubusercontent.com/50344708/82220871-cf725a00-9951-11ea-9910-df102d13e44b.png)

**Info (please complete the following information):**
 - Server version: spigot1.15.2
 - Client version: fabric 1.15.2 with wwe
 - Plugin version: 2.0.22

**Additional context**
[21:35:48] [Server thread/INFO]: ___dofu___ issued server command: /iareload
[21:35:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iareload' in plugin ItemsAdder v2.0.22
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[?:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[?:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
        at dev.lone.itemsadder.d.b.b.b.s(SourceFile:192) ~[?:?]
        at dev.lone.itemsadder.c.k.onCommand(SourceFile:34) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-d07a78b]
        ... 17 more

**Comment by LoneDev6** [comment]
duplicate, fixed in new release i will publish today
