### ISSUE TITLE
[Arclight 1.0.25] Could not pass event BlockBreakEvent to ItemsAdder v3.4.1

### ISSUE THREAD

**Issue by reiyooki** [LoneDev6/ItemsAdder#2476]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

reiyo_oki#4669

### What happened?

Upon breaking any of our custom blocks (Created using the wiki template/guide) we receive an error in the console. Unsure if this is Arclight specific or not, but I didn't see any exact matches for the error when searching.

This occurs with any of our custom blocks, I just picked a random one as an example, they're all formatted the same way.

### Steps to reproduce the issue

1. Place any custom block
2. Break the custom block by hand. (Worldedit replace/cut don't cause the error)

### Server version

arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### ItemsAdder Version

ItemsAdder version 3.4.1

### ProtocolLib Version

ProtocolLib version 4.8.0

### LoneLibs Version

LoneLibs version 1.0.24

### FULL server log

[debug.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11114810/debug.log)
[latest.log](https://github.com/PluginBugs/Issues-ItemsAdder/files/11114811/latest.log)

### Error (optional)

```shell
[30Mar2023 18:16:38.972] [Server thread/ERROR] [Minecraft/]: Could not pass event BlockBreakEvent to ItemsAdder v3.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at io.izzel.arclight.common.mod.server.event.BlockBreakEventDispatcher.onBreakBlock(BlockBreakEventDispatcher.java:29) ~[arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar:arclight-1.16.5-1.0.25-SNAPSHOT-aeef36e9]
	at net.minecraftforge.eventbus.ASMEventHandler_36_BlockBreakEventDispatcher_onBreakBlock_BreakEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooksMixin.java:595) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManagerMixin.java:230) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManagerMixin.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManagerMixin.java:614) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandlerMixin.java:2178) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.md3117ac$lambda$checkThreadAndEnqueue$0$0(PacketThreadUtilMixin.java:536) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServerMixin.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServerMixin.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServerMixin.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServerMixin.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1921) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.block.BlockState net.minecraft.world.chunk.Chunk.getBlockData(net.minecraft.util.math.BlockPos)'
	at ia.nms.aB.impl.v1_16_R3.H(SourceFile:203) ~[?:?]
	at ia.m.ck.d(SourceFile:684) ~[?:?]
	... 29 more
```

### Problematic items yml configuration file (optional)

```shell
info:
  namespace: pokemc
items:
  smw_bonus_block:
    display_name: Bonus Block
    permission: smw
    resource:
      generate: true
      material: PAPER
      textures:
        - block/bonus_block
    specific_properties:
      block:
        placed_model:
          type: REAL_NOTE
          break_particles: ITEM
        cancel_drop: true
```

**Comment by LoneDev6** [comment]
Will be checked as soon as possible
