### ISSUE TITLE
[BUG] Una spada difficile da aggiungere

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#251]
[https://cdn.discordapp.com/attachments/414537824528760832/711566766538620978/assets.rar](url)

Ciao, nel link che ti ho dato c'è una spada.
Non riesco ad aggiungerla. Mi da questo risultato in gioco:

![image](https://user-images.githubusercontent.com/20026629/82268461-5681fb00-996f-11ea-932f-a2674553be04.png)

E chiaramente non è il risultato previsto.

Ho inserito i file i questo modo:

>   sebastiano17_sword:
    display_name: Sebastiano17 Sword
    permission: sebastiano17_sword
    resource:
      material: DIAMOND_SWORD
      generate: false
      model_path: item/sebastiano17_sword
    durability:
      max_custom_durability: 2000
    attribute_modifiers:
      mainhand:
        attackDamage: 20.0

Nella cartella **plugins\ItemsAdder\data\resource_pack\assets\survivalla\textures\item\sebastiano17_sword**

Ho messo i file png e mcmeta

Invece nella cartella **plugins\ItemsAdder\data\resource_pack\assets\survivalla\models\item**

Ho messo il file json

Come devo metterli i file? li metto male?
Ho seguito la guida [https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/resource#use-your-own-custom-model](url)

**Comment by Fargus5** [comment]
Ho seguito la guida:
[https://itemsadder.plugin.ga/plugin-usage/adding-content/item-properties/resource#use-your-own-custom-model](url)

**Comment by LoneDev6** [comment]
Modifica in questo modo il .json:

```Json
"textures": {
    "texture": "survivalla:items/gold_sword"
},
```

**Comment by Fargus5** [comment]
[19:39:53 ERROR]: [ItemsAdder] §cError loading the plugin, something is not configured right or an exception occured. More detail:
[19:39:53 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GOLD_SWORD
[19:39:53 WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[19:39:53 WARN]: 	at org.bukkit.Material.valueOf(Material.java:1)
[19:39:53 WARN]: 	at dev.lone.itemsadder.j.d.a(SourceFile:258)
[19:39:53 WARN]: 	at dev.lone.itemsadder.j.d.a(SourceFile:264)
[19:39:53 WARN]: 	at dev.lone.itemsadder.d.b.h(SourceFile:303)
[19:39:53 WARN]: 	at dev.lone.itemsadder.d.b.a(SourceFile:231)
[19:39:53 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83)
[19:39:53 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[19:39:53 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[19:39:53 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[19:39:53 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:39:53 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:39:53 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Fargus5** [comment]
In teoria si chiama Golden Sword.

Comunque avevo già provato modificando quel valore, ho messo anche Diamond Sword ma niente

[19:45:21 ERROR]: [ItemsAdder] §cError loading the plugin, something is not configured right or an exception occured. More detail:
[19:45:21 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.GOLD_SWORD
[19:45:21 WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[19:45:21 WARN]: 	at org.bukkit.Material.valueOf(Material.java:1)
[19:45:21 WARN]: 	at dev.lone.itemsadder.j.d.a(SourceFile:258)
[19:45:21 WARN]: 	at dev.lone.itemsadder.j.d.a(SourceFile:264)
[19:45:21 WARN]: 	at dev.lone.itemsadder.d.b.h(SourceFile:303)
[19:45:21 WARN]: 	at dev.lone.itemsadder.d.b.a(SourceFile:231)
[19:45:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83)
[19:45:21 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
[19:45:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
[19:45:21 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
[19:45:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
[19:45:21 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
[19:45:21 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Fargus5** [comment]
Ho provato mettendo con il namespace e con golden 
mi da come risultato una Ruby Dagger.
quindi niente

**Comment by Fargus5** [comment]
"textures": {
    "texture": "survivalla:items/gold_sword"
},

Questo è sbagliato.

C'è una s di troppo e non ci va il namespace.

**Comment by Fargus5** [comment]
La spada cosi si vede....

puoi confermarmi che la procedura è corretta?

**Comment by LoneDev6** [comment]
> 
> 
> La spada cosi si vede....
> 
> puoi confermarmi che la procedura è corretta?

se il percorso `item/sebastiano17_sword/sebastiano17_sword` è corretto sì.
comunque ti invito gentilmente a evitare di scrivere a getto qui, fai tutte le prove, se non risolvi chiedi, altrimenti ricevo una email per ogni messaggio

piuttosto modifica il messaggio originale aggiungendo dettagli
