### ISSUE TITLE
[BUG] While trying iareload have this exception.

### ISSUE THREAD

**Issue by idevmans** [LoneDev6/ItemsAdder#272]
**Describe the bug**
I just type iareload but before i am deleted from folder data items_pack, and from ia_gui emojies.

**To Reproduce**
1. Described above.

**Expected behavior**
I excpect it will reloaded and do not show to me examples file.

**Info (please complete the following information):**
 - Server version: (example: spigot 1.15.2)
 - Client version: (example: fabric 1.15.2)
 - Plugin version: (latest from spigotmc)

```
[14:43:42] [Craft Scheduler Thread - 914/WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.24 generated an exception while executing task 8689
java.lang.NullPointerException: null
        at dev.lone.itemsadder.g.a.Q(SourceFile:92) ~[?:?]
        at dev.lone.itemsadder.g.d.<init>(SourceFile:84) ~[?:?]
        at dev.lone.itemsadder.d.b.a(SourceFile:1030) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83) ~[start.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [start.jar:git-Spigot-2f5d615-d07a78b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
>
```

**Comment by LoneDev6** [comment]
To remove my items you have to open config.yml and set this:
  extract-default-items: false
  extract-default-resources: false
