### ISSUE TITLE
[BUG] Crash

### ISSUE THREAD

**Issue by yttalium** [LoneDev6/ItemsAdder#278]
Hello !
I rebooted my official server (so this is a more serious problem) and since the plugin crashed on reboot. I haven't made any modifications to the plugin for a few weeks.

**Info :**
 - Server version: 1.15.2
 - Client version: Paper 1.15.2 #332
 - Plugin version: 2.0.24

``[19:44:57] [Server thread/INFO]: [ItemsAdder] Enabling ItemsAdder v2.0.24
[19:44:57] [Server thread/INFO]: ------ ItemsAdder ------
[19:44:57] [Server thread/INFO]:                                                             
[19:44:57] [Server thread/INFO]:                                                             
[19:44:57] [Server thread/INFO]: Failed to get username for: 524664
[19:44:57] [Server thread/INFO]: Loading data...
[19:44:57] [Server thread/INFO]: Registered Skript API
[19:44:57] [Server thread/INFO]: Found resourcepack folder: /root/yttalium/plugins/ItemsAdder/data/resource_pack
[19:44:57] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.0.24 (Is it up to date?)
dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:59) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTFile.<init>(SourceFile:36) ~[?:?]
	at dev.lone.itemsadder.d.d.a.b.b.b.<init>(SourceFile:58) ~[?:?]
	at dev.lone.itemsadder.d.b.b(SourceFile:198) ~[?:?]
	at dev.lone.itemsadder.d.b.<init>(SourceFile:155) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:107) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: dev.lone.itemsadder.Libs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:153) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
Caused by: net.minecraft.server.v1_15_R1.ReportedException: Loading NBT data
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:123) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:86) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:25) ~[patched_1.15.2.jar:git-Paper-332]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_242]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_242]
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117) ~[?:1.8.0_242]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_242]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_242]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_242]
	at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_242]
	at java.io.DataInputStream.readUTF(DataInputStream.java:609) ~[?:1.8.0_242]
	at java.io.DataInputStream.readUTF(DataInputStream.java:564) ~[?:1.8.0_242]
	at net.minecraft.server.v1_15_R1.NBTTagCompound.d(NBTTagCompound.java:439) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTTagCompound.access$100(NBTTagCompound.java:23) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:39) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTTagCompound$1.b(NBTTagCompound.java:27) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:117) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:86) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:25) ~[patched_1.15.2.jar:git-Paper-332]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(SourceFile:151) ~[?:?]
	at dev.lone.itemsadder.Libs.nbt.nbtapi.NBTReflectionUtil.readNBT(SourceFile:57) ~[?:?]
	... 14 more
[19:44:57] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.0.24
[19:44:57] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[19:44:57] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v2.0.24 (Is it up to date?)
java.lang.NullPointerException: null
	at dev.lone.itemsadder.Main.onDisable(SourceFile:169) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-332]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-332]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-332]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]``

**Comment by yttalium** [comment]
I finally found the solution! In a rush of despair I deleted the regions_data file and it worked. Fortunately the worlds where this generated minerals were in mining worlds.
Maybe put this error in the F.A.Q ?

**Comment by LoneDev6** [comment]
Really strange, this doesn't seem related to region_data as if a region file is corrupted the plugin would delete it without crashing.
Anyway please use pastebin for errors or similar hasteb.in, it's easier to read.

Thanks!
