### ISSUE TITLE
[BUG] Unable to pass Chunk Load

### ISSUE THREAD

**Issue by PhanaticD** [LoneDev6/ItemsAdder#287]
**Describe the bug**
I was hoping to upgrade itemsadder 1.x->2.x before finally updating my server from 1.14.4 to 1.15.2 however this issue happened, I am guessing only 1.15.2 is supported but it does say 1.14.4 on the plugin page

```
[06:13:31] [Server thread/ERROR]: Could not pass event ChunkLoadEvent to ItemsAdder v2.0.26
java.lang.NoClassDefFoundError: org/bukkit/HeightMap
        at dev.lone.itemsadder.a.a(SourceFile:268) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.Chunk.loadCallback(Chunk.java:644) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$7(PlayerChunk.java:415) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$8(PlayerChunk.java:413) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_231]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_231]
        at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:94) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:814) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:426) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1064) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1048) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1032) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:955) ~[skyblock.jar:git-Craftimize-"9d09705"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]

```

**Comment by LoneDev6** [comment]
This will be fixed in next update, I didn't know that 1.14 didn't have the HeightMap class.
