### ISSUE TITLE
PlayerInteractEvent Error when Shooting Mob

### ISSUE THREAD

**Issue by 00Hrtz** [LoneDev6/ItemsAdder#2908]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I already searched on this [Github page](https://github.com/PluginBugs/Issues-ItemsAdder/issues) to check if the same issue was already reported.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.

### Discord tag (optional)

sircraftypants#4875

### What happened?

While shooting mobs with a gun, this error was spamming.

### Steps to reproduce the issue

Using the below Gun i shot mobs.

Gun Configuration https://paste.helpch.at/yabariwiko.yaml

### Server version

[04:18:17 INFO]: This server is running Paper version git-Paper-98 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: a40e48f)
You are running the latest version
Previous version: git-Paper-95 (MC: 1.20.1)

### ItemsAdder Version

version itemsAdder
[04:14:18 INFO]: ItemsAdder version 3.5.0c-r2
[04:14:18 INFO]: Customized Minecraft without client mods!
[04:14:18 INFO]: Website: devs.beer
[04:14:18 INFO]: Author: LoneDev

### ProtocolLib Version

version protocolLib
[04:14:50 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-661
[04:14:50 INFO]: Provides read/write access to the Minecraft protocol.
[04:14:50 INFO]: Authors: dmulloy2 and comphenix

### LoneLibs Version

version lonelibs
[04:13:51 INFO]: LoneLibs version 1.0.25
[04:13:51 INFO]: Collection of libs used by my plugins
[04:13:51 INFO]: Authors: LoneDev and others

### Error (optional)

```shell
[04:05:50 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v3.5.0c-r2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_20_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader java.net.URLClassLoader @32a1bec0)
        at ia.m.di.a(SourceFile:36) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dS.a(SourceFile:40) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dS.a(SourceFile:58) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.bM.c(SourceFile:263) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.cZ.a(SourceFile:768) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.er.a(SourceFile:551) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.bM.b(SourceFile:262) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dd.a(SourceFile:145) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at ia.m.dd.h(SourceFile:235) ~[ItemsAdder_3.5.0c-r2.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-98]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-98]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:523) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:517) ~[paper-1.20.1.jar:git-Paper-98]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:513) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2018) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-98]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-98]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SirCraftypants** [comment]
apologies in advance if it''s human error, believe it or not this is the first time i've attempted to add guns.

a small question too, is it possible to set the projectile so that it only needs you to have 1 projectile item and it have a usage count. so amount 1 of the projectile equates to 30 shots?

**Comment by LoneDev6** [comment]
> a small question too, is it possible to set the projectile so that it only needs you to have 1 projectile item and it have a usage count. so amount 1 of the projectile equates to 30 shots?

No it's not possible, guns projectiles only use item amount

**Comment by SirCraftypants** [comment]
Still occurring in r4, have noticed you've tagged it r5 also, just letting you know. 

https://paste.helpch.at/lefafizebi.rb
