### ISSUE TITLE
[BUG] PlayerInteractEvent exception

### ISSUE THREAD

**Issue by 100petr** [LoneDev6/ItemsAdder#329]
**Describe the bug**
Error https://pastebin.com/tbZ4r7RU

**To Reproduce**
Idk, sorry

**Expected behavior**
no error

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.16.1
 - Client version: all players have 1.16.1
 - Plugin version: 2.0.38

**Additional context**

**Comment by LoneDev6** [comment]
Please check your logs, surely previously you got the complete error, this is only a portion of it and I cannot identify where it came from.
Thanks for the help

**Comment by 100petr** [comment]
I did not find any other ia error.
[2020-07-17-7.log](https://github.com/LoneDev6/ItemsAdder/files/4941509/2020-07-17-7.log)

**Comment by LoneDev6** [comment]
Found it in your log:
```
[22:00:07] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.0.38
java.lang.NullPointerException: null
	at dev.lone.itemsadder.e.e.c.b.h.h(SourceFile:68) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.1.jar:git-Paper-93]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-93]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:497) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:459) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1453) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-93]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-93]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```






ALSO:

This is not related to IA but i noticed you forgot to cange PIG_ZOMBIE to the [ZOMBIFIED_PIGLIN ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html#ZOMBIFIED_PIGLIN)in SoulJars :
```
[16:55:31] [Server thread/INFO]: [SoulJars] Enabling SoulJars vDEV - 16 (git 36dce719)
[16:55:31] [Server thread/ERROR]: [SoulJars] IllegalArgumentException: Possibly invalid mob type: PIG_ZOMBIE
```

**Comment by 100petr** [comment]
Yes, I noticed. After sending the log, I fixed it. But thanks.
