### ISSUE TITLE
[BUG] Incompatibility with ArmoredElytra in the latest versions

### ISSUE THREAD

**Issue by Alejitus** [LoneDev6/ItemsAdder#336]
I receive the following error when updating.

```
[Server thread/WARN]: [ItemsAdder] Loaded class com.codingforcookies.armorequip.ArmorEquipEvent from ArmoredElytra v2.4.14 which is not a depend, softdepend or loadbefore of this plugin.

[Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.0.40 (Is it up to date?)
java.lang.NoSuchMethodError: com.codingforcookies.armorequip.ArmorListener: method <init>()V not found
	at dev.lone.itemsadder.Main.onEnable(SourceFile:149) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-101]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
```

 - Server version: Paper 1.16.1 (# 101)
 - Plugin version: 2.0.40 and the previous one (when you upgraded to LoneLibs).

In previous versions (with IALibs) it works correctly. I did a clean install and the same thing happens when I add the ArmoredElytra plugin.

**Comment by SgtLegoTown** [comment]
i have the same problem hope my information helps

ItemsAdder Conflict Error : https://pastebin.com/z7eJzP7v
Full Serverlog after removing ArmoredElyctra plugin no more errors : https://pastebin.com/tTyfkqsp
Full Serverlog With Error and ArmoredElyctra plugin active : https://pastebin.com/vWWCeHvB

i add it here becouse i think its the same error only trying to provide extra info

**Comment by LoneDev6** [comment]
Fixed in latest update
