### ISSUE TITLE
ArmorEquipEvent [BUG] 

### ISSUE THREAD

**Issue by mraid29** [LoneDev6/ItemsAdder#348]
**Describe the bug**
the console disable s the plugin with this message upon startup

[21:48:44 WARN]: [ItemsAdder] Loaded class com.codingforcookies.armorequip.ArmorEquipEvent from ArmorEquipEvent v1.7.2 which is not a depend, softdepend or loadbefore of this plugin.
[21:48:45 ERROR]: Error occurred while enabling ItemsAdder v2.0.40 (Is it up to date?)
java.lang.NoSuchMethodError: com.codingforcookies.armorequip.ArmorListener: method <init>()V not found
at dev.lone.itemsadder.Main.onEnable(SourceFile:149) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-131]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[21:48:45 INFO]: [ItemsAdder] Disabling ItemsAdder v2.0.40
[21:48:45 INFO]: [ItemsAdder] All worlds: saved 0 regions
[21:48:45 INFO]: [ItemsAdder] Saved 0 player stats files

**To Reproduce**
1. download the plugin and its three dependancies, run the server

**Expected behavior**
the plugin to activate

**Screenshots**

**Info (please complete the following information):**
 - Server version: paper 1.16.1
 - Plugin version:  2.0.40

**Additional context**

**Comment by LoneDev6** [comment]
Update ItemsAdder and LoneLibs
