### ISSUE TITLE
[BUG] meet error when start server

### ISSUE THREAD

**Issue by Sapherises** [LoneDev6/ItemsAdder#349]
**Describe the bug**
when i start server and meet this error from time to time

[09:20:15] [Craft Scheduler Thread - 48/WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.41 generated an exception while executing task 1664
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:997) ~[?:?]
	at dev.lone.itemsadder.e.h.b.c.b(SourceFile:106) ~[?:?]
	at dev.lone.itemsadder.e.h.b.c.b(SourceFile:117) ~[?:?]
	at dev.lone.itemsadder.h.c.a(SourceFile:72) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-134]
	at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-134]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-134]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Expected behavior**

This problem arises from time to time. If there is an error in the service opening, the screen will be swiped later. And players can't destroy the furniture that has been placed

**Screenshots**

[latest.log](https://github.com/LoneDev6/ItemsAdder/files/5056050/latest.log)

 - Server version: 1.16.1
 - Client version:  1.16.1
 - Plugin version:  2.0.41

**Comment by LoneDev6** [comment]
Should be related to the converter, you can disable it if your server is completely converted from 1.0
