### ISSUE TITLE
[BUG] Exception and Error Plugin Disabled

### ISSUE THREAD

**Issue by SirCraftypants** [LoneDev6/ItemsAdder#364]
**Describe the bug**

[15:08:45 WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.38 generated an exception while executing task 23066
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.paper
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
at org.bukkit.Material.valueOf(Material.java:85) ~[patched_1.15.2.jar:git-Paper-378]
at dev.lone.itemsadder.e.b.a(SourceFile:1455) ~[?:?]
at dev.lone.itemsadder.e.b.a(SourceFile:767) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-378]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-378]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**To Reproduce**

I added a lot of new textures to Itemsadder
restarted the server after installing the updates
ran /iatexture all
ran /iareload

got this warn above and now the menu will not open.

So updated to latest version 2.0.42 and now have this error

[15:29:04 INFO]: Sir_Craftypants issued server command: /ia
[15:29:04 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v2.0.42 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1866) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1674) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Expected behavior**
I expected my textures to load into the itemsadder menu and for everything to be fine, I was attempting to get my textures to load properly.

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Plugin version: 2.0.42

**Additional context**
I just wanted my textures to load properly and now this, i did contact you before hand for help with the textures not loading. Gone from bad to worse.

**Comment by LoneDev6** [comment]
Change paper to PAPER in one of your configs.
Be sure to use these names for materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

**Comment by SirCraftypants** [comment]
I went through every single config i have and everything capitalised, restarted my server and:

[03:35:45 INFO]: Product licensed to: sir_craftypants
[03:35:45 INFO]: Loading data...
[03:35:45 INFO]: Found resourcepack folder: /home/container/plugins/ItemsAdder/data/resource_pack
[03:35:45 ERROR]: [ItemsAdder] Plugin ItemsAdder v2.0.42 has failed to register events for class dev.lone.itemsadder.e.e.c.b.a because dev/lone/LoneLibs/armorequip/ArmorEquipEvent does not exist.
[03:35:45 ERROR]: Error occurred while enabling ItemsAdder v2.0.42 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/lone/LoneLibs/armorequip/ArmorListener
at dev.lone.itemsadder.Main.onEnable(SourceFile:149) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: dev.lone.LoneLibs.armorequip.ArmorListener
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 10 more

Then i updated Lonelibs to the latest version and then 

[03:39:14 ERROR]: Could not load 'plugins/LoneLibs.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_242]
at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_242]
at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_242]
at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_242]
at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_242]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.15.2.jar:git-Paper-378]
... 5 more
[03:39:15 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[03:39:19 WARN]: Legacy plugin ColoredSigns v3.0 does not specify an api-version.
[03:39:19 WARN]: Legacy plugin VoidWorld v1.0 does not specify an api-version.
[03:39:19 WARN]: Legacy plugin Multiverse-portalsGUI v1.0 does not specify an api-version.
[03:39:19 ERROR]: Could not load 'plugins/ItemsAdder.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency LoneLibs. Please download and install LoneLibs to run this plugin.
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:39:19 WARN]: Legacy plugin BookNews v4.11 does not specify an api-version.
[03:39:19 WARN]: Legacy plugin PetBlocks v8.21.0 does not specify an api-version.
[03:39:19 WARN]: Legacy plugin LightAPI v3.4.3 does not specify an api-version.
[03:39:19 ERROR]: Could not load 'plugins/EpicBackPacks.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency LoneLibs. Please download and install LoneLibs to run this plugin.
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[03:39:19 WARN]: Legacy plugin CustomHeads v3.0.2 does not specify an api-version.
[03:39:21 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@229dc8f]
[03:39:21 INFO]: WEPIF: Using the Bukkit Permissions API.
[03:39:22 INFO]: Candidate: com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R1
[03:39:22 WARN]: com.sk89q.worldedit.bukkit.adapter.impl.FAWE_Spigot_v1_16_R1 is not custom candidate.
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/NBTBase
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_242]
at com.sk89q.worldedit.bukkit.adapter.BukkitImplLoader.loadAdapter(BukkitImplLoader.java:160) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.loadAdapter(WorldEditPlugin.java:392) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.setupPreWorldData(WorldEditPlugin.java:236) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.onEnable(WorldEditPlugin.java:217) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-378]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.init(WorldEditPlugin.java:165) ~[?:?]
at com.sk89q.worldedit.bukkit.WorldEditPlugin.<init>(WorldEditPlugin.java:149) ~[?:?]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_242]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:137) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.NBTBase
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 22 more

**Comment by SirCraftypants** [comment]
And now i'm getting 

[03:46:26 ERROR]: Could not load 'plugins/EpicBackPacks.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency LoneLibs. Please download and install LoneLibs to run this plugin.
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:272) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

This is getting ridiculous, this weekend was supposed to be my last summer holiday week with my Son but because I'm on a deadline to get my Server ready for November 30th I've had to put all my time into trying to fix this. spent 5 days on this, was supposed to be just a simple task of adding textures and has turned in to an almighty mess.

**Comment by SirCraftypants** [comment]
Ok i've solved the lonelibs issue, the spigot download is broken, i used the alternative download you provided on the same page. attempting to fix the other issue.

**Comment by LoneDev6** [comment]
About the PAPER error please enable these settings in config.yml and look in logs for the problematic item/recipe/loot:
log-items-loading: true
log-recipes-loading: true
log-loots-loading: true

> This is getting ridiculous, this weekend was supposed to be my last summer holiday week with my Son but because I'm on a deadline to get my Server ready for November 30th I've had to put all my time into trying to fix this. spent 5 days on this, was supposed to be just a simple task of adding textures and has turned in to an almighty mess.

I'm really sorry for this., downloading the LoneLibs.jar file directly from the alternative link will surely work, it's a known SpigotMC.org bug I hope they will fix in the future.
Let me know if you still have problems installing the plugin.

Have a nice day

**Comment by SirCraftypants** [comment]
Ok I've fixed all the Items and Recipes, all are loading fine but still getting this 


[17:56:05 WARN]: [ItemsAdder] Plugin ItemsAdder v2.0.42 generated an exception while executing task 4062
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.egg
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_242]
at org.bukkit.Material.valueOf(Material.java:85) ~[patched_1.15.2.jar:git-Paper-378]
at dev.lone.itemsadder.e.b.a(SourceFile:1455) ~[?:?]
at dev.lone.itemsadder.e.b.a(SourceFile:878) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-378]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-378]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

[17:56:06 WARN]: [ItemsAdder] Task #4107 for ItemsAdder v2.0.42 generated an exception
java.lang.IllegalArgumentException: Symbol does not appear in the shape:112
at org.apache.commons.lang.Validate.isTrue(Validate.java:93) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.inventory.ShapedRecipe.setIngredient(ShapedRecipe.java:142) ~[patched_1.15.2.jar:git-Paper-378]
at dev.lone.itemsadder.e.h.c.c.a(SourceFile:54) ~[?:?]
at dev.lone.itemsadder.e.b.a(SourceFile:832) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-378]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-378]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-378]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by SirCraftypants** [comment]
Hi, I've fixed everything but still getting these and I don't understand what's causing them?

https://paste.helpch.at/mukuzudage.coffeescript

**Comment by SirCraftypants** [comment]
OK i've fixed the bucket error but the others i dont know how too.

**Comment by SirCraftypants** [comment]
Ok now it's only these

https://paste.helpch.at/ezujidivix.css

**Comment by SirCraftypants** [comment]
Now more and I can't understand them because they're not telling me what to look for like the ones i have now fixed?

https://paste.helpch.at/ikikozotan.css

**Comment by SirCraftypants** [comment]
Ok I just don't understand whats wrong.

Everything I've added works perfectly and itemsadder is running ok BUT

https://paste.helpch.at/fokujowazo.css

**Comment by LoneDev6** [comment]
Install the new update and restart.
It will print in console which recipe is misconfigured so that you can fix it.


Please don't keep sending messages and deleting them, just send one and edit it, I get an email for each message

**Comment by SirCraftypants** [comment]
Sorry about that, superb update, it showing us what is wrong is going to make your life much easier, i'll keep doing my best to help on your discord channel. Thanks for your time and help.

**Comment by LoneDev6** [comment]
No problem ;)

I also released a tool that could help you, it autocompletes text and also shows you if you made any mistake.
Keep in mind that it's in beta: https://ide.plugin.ga/itemsadder/
