### ISSUE TITLE
[BUG] A large number of duplicate error messages appear in the plugin startup console

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#375]
**Describe the bug**
An error occurred when the plugin started,the /ia command can be used normally in the game

**Info (please complete the following information):**
 - Server version:  paper 1.16.2 git-Paper-176
 - Plugin version: v 2.0.43

**Additional context**
`Could not pass event ChunkLoadEvent to ItemsAdder v2.0.43
java.lang.NullPointerException: null
        at org.bukkit.craftbukkit.v1_16_R2.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.2.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:516) ~[patched_1.16.2.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.getBiome(CraftWorld.java:1087) ~[patched_1.16.2.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlock.getBiome(CraftBlock.java:503) ~[patched_1.16.2.jar:git-Paper-176]
        at dev.lone.itemsadder.e.e.a.b.b.b.a(SourceFile:482) ~[?:?]
        at dev.lone.itemsadder.e.e.a.b.b.b.b(SourceFile:99) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor364.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-176]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-176]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-176]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.Chunk.loadCallback(Chunk.java:815) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$15(PlayerChunk.java:744) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1054) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.runTasks(ChunkProviderServer.java:636) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1144) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.2.jar:git-Paper-176]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-176]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by LoneDev6** [comment]
Are you using a custom datapack that adds biomes?

**Comment by LoneDev6** [comment]
https://github.com/LoneDev6/ItemsAdder/issues/367

**Comment by yebanme** [comment]
> Are you using a custom datapack that adds biomes?

Yes, I added the packet for the nether biome

**Comment by LoneDev6** [comment]
Fixed in next update https://github.com/LoneDev6/ItemsAdder/issues/367
