### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lcbathtissue** [LoneDev6/ItemsAdder#376]
Got the below errors in console after trying airplanes/vehicles on 1.16.2 paper

[19:57:42] [Server thread/ERROR]: Could not pass event BlockMultiPlaceEvent to ItemsAdder v2.0.44
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:345) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.ItemStack.placeItem(ItemStack.java:218) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:491) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1278) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
	at dev.lone.itemsadder.e.e.a.b.i.a(SourceFile:149) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.addEntity(CraftWorld.java:1796) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1806) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1394) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]
	at dev.lone.itemsadder.e.e.a.b.i.b(SourceFile:131) ~[?:?]
	at dev.lone.itemsadder.e.e.a.b.i.a(SourceFile:83) ~[?:?]
	at dev.lone.itemsadder.e.e.c.b.a(SourceFile:84) ~[?:?]
	at dev.lone.itemsadder.e.e.c.b.g(SourceFile:276) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot.jar:git-Spigot-3a70bd9-bf3d720]

**Comment by LoneDev6** [comment]
Invalid bug report, removed the whole template. No info provided other than the error
