### ISSUE TITLE
Trying to place vehicles error on 1.16.3

### ISSUE THREAD

**Issue by antibitcoin** [LoneDev6/ItemsAdder#378]
**Error:**

>.... [23:38:17 ERROR]: POI data mismatch: never registered at BlockPosition{x=2147, y=64, z=1971}
>.... [23:38:19 ERROR]: Could not pass event BlockMultiPlaceEvent to ItemsAdder v2.0.44
java.lang.NullPointerException: null
at dev.lone.itemsadder.e.e.a.b.i.a(SourceFile:149) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.addEntity(CraftWorld.java:1975) ~[patched_1.16.3.jar:git-Paper-193]
at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1985) ~[patched_1.16.3.jar:git-Paper-193]
at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1564) ~[patched_1.16.3.jar:git-Paper-193]
at dev.lone.itemsadder.e.e.a.b.i.b(SourceFile:131) ~[?:?]
at dev.lone.itemsadder.e.e.a.b.i.a(SourceFile:83) ~[?:?]
at dev.lone.itemsadder.e.e.c.b.a(SourceFile:84) ~[?:?]
at dev.lone.itemsadder.e.e.c.b.g(SourceFile:276) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-193]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-193]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-193]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-193]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callBlockMultiPlaceEvent(CraftEventFactory.java:351) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.ItemStack.placeItem(ItemStack.java:278) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:528) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1449) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-193]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-193]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

Installed plugins:
AdvancedEnchantments, AntiCheatReloaded, AntiSeedCracker, ArmorStandEditor, AuctionHouse, AutoBroadcast, Bank, BetterSleeping3, BuycraftX, Citizens, CitizensCMD, Clans, ClansChatAddon, ClansChestAddon, ClansCreateAddon, ClansRenameAddon, ClansShowAddon, ClansStatsAddon*, CommandAlias, Core, CustomHeads*, DailyBonus, DeathMessagesPrime, DiscordSRV, DynamicIcon*, EnchantmentLock, Essentials, EZColors, FrozenJoin, HolographicDisplays, IllegalStack, ImageOnMap, Item2Chat, ItemEditor, ItemsAdder, LagAssist, LightAPI*, LoneLibs, Lottery, LPC, LuckPerms, MapManager, OpenInv, PacketListenerApi*, PL-Hide, PlaceholderAPI, PlayerListDeluxe*, PlayerParticles, PlayerVaults, Playtimes*, PlugMan, ProtocolLib, QuickBoard*, SaveRodOfficial*, Sentinel, ShopGUIPlus, SilentBans*, SilkSpawners, SimpleRename, SpecializedCrates, TCPShield*, UltimateAutoRestart, Vault, ViaBackwards, ViaVersion, VoteParty, Votifier, VotingPlugin, Wands, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by LoneDev6** [comment]
Please don't erase the issue template, open a new issue and specify every info required, thanks!
