### ISSUE TITLE
Destroy impossible object

### ISSUE THREAD

**Issue by SharkblackFr** [LoneDev6/ItemsAdder#385]
when I try to destroy a custom object I can’t. Can you help me?

**Comment by PokeMy14** [comment]
The same thing here... Im using spigot 1.14.4. and the emojis doesn't work too.

**Comment by SharkblackFr** [comment]
same  version use

**Comment by LoneDev6** [comment]
Break error:

```
[20:52:02] [Server thread/WARN]: [ItemsAdder] Task #1819 for ItemsAdder v2.0.46 generated an exception
java.lang.NoSuchFieldError: BEEHIVE
        at dev.lone.itemsadder.k.l.<clinit>(SourceFile:27) ~[?:?]
        at dev.lone.itemsadder.e.e.a.b.a.a(SourceFile:130) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

@PokeMy14 please send your log, I need errors to fix.
Also, did you read here: https://itemsadder.plugin.ga/faq/huds-emojis-guis-font/i-cant-see-emoji-guis-huds

**Comment by LoneDev6** [comment]
Anyway, I really suggest you to update to Spigot 1.15.2, why staying 1.14.4? It's really laggy

**Comment by PokeMy14** [comment]
@LoneDev6 Okey, thanks, I'm going to try with version 1.15.2, in case it doesn't work I'll show you the error. We are in contact.

**Comment by SharkblackFr** [comment]
I currently need the plugin compatible in 1.14.4 for my part if is possible

**Comment by LoneDev6** [comment]
> 
> 
> I currently need the plugin compatible in 1.14.4 for my part if is possible

Can you please send me your COMPLETE server log?
Are you running a spigot unofficial fork?

**Comment by LoneDev6** [comment]
I should have fixed that, I will post an update this week
