### ISSUE TITLE
[BUG] /itag error when using it without item in hand.

### ISSUE THREAD

**Issue by GHsorryiwon12345** [LoneDev6/ItemsAdder#386]
**Describe the bug**
Errors appears in console when using /iatag without item in hand.

**To Reproduce**
1. Use /iatag without item in hand (air)

**Expected behavior**
error appears in console.

**Screenshots**

![image](https://user-images.githubusercontent.com/43861907/93815732-bb6b9b80-fc56-11ea-9468-872983737475.png)

**Info (please complete the following information):**
 - Server version: (paper 1.16.1)
 - Client version: (fabric 1.16.1)
 - Plugin version: (2.0.48)

**Additional context**

[22:06:25 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iatag' in plugin ItemsAdder v2.0.48
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-136]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-136]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-136]        at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1266) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NullPointerException: ItemStack can't be null/Air!
        at dev.lone.LoneLibs.nbt.nbtapi.NBTItem.<init>(NBTItem.java:28) ~[?:?]
        at dev.lone.itemsadder.d.o.onCommand(SourceFile:42) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-136]
        ... 18 more

**Comment by LoneDev6** [comment]
Thanks I will fix this in next update
