### ISSUE TITLE
[BUG] Reloading the plugin console while the plugin saves data will output an error

### ISSUE THREAD

**Issue by yebanme** [LoneDev6/ItemsAdder#393]
**Describe the bug**
If the /iareload command is executed when the plugin is automatically saved, an error will occur

**To Reproduce**
1. Wait for the console output plugin to automatically save the information
2. Execute the /iareload command at the beginning of autosave
3. See error

**Expected behavior**
The plugin reloads without errors

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Plugin version: latest

**Additional context**
`[23:09:46 INFO]: [ItemsAdder] Saved 0 player stats files
[23:09:47 INFO]: [ItemsAdder] Saved 0 player stats files
[23:09:47 INFO]: [ItemsAdder] Saved 0 player stats files
[23:09:47 INFO]: [ItemsAdder] world: saved 0 regions
[23:09:47 INFO]: [ItemsAdder] world_nether: saved 0 regions
[23:09:47 INFO]: [ItemsAdder] world_the_end: saved 0 regions
> iareload
[23:09:48 INFO]: [ItemsAdder] Found resourcepack folder: F:\Minecraft\plugins\ItemsAdder\data\resource_pack
[23:09:48 INFO]: [ItemsAdder] Reloaded items_packs and resource_pack
[23:09:48 INFO]: [ItemsAdder] Saved 0 player stats files
[23:09:48 INFO]: [ItemsAdder] Resourcepack initialization...
[23:09:48 INFO]: [ItemsAdder]     Checking for online default resourcepack updates...
[23:09:48 ERROR]: [ItemsAdder] Corrupted region data! Moving it into 'corrupted_data' folder: world/r.1.0.nbt
[23:09:48 WARN]: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
[23:09:48 WARN]:        at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:59)
[23:09:48 WARN]:        at dev.lone.LoneLibs.nbt.nbtapi.NBTFile.<init>(NBTFile.java:36)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.b.b.<init>(SourceFile:19)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.b.a.<init>(SourceFile:19)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.d.b(SourceFile:96)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.b.a(SourceFile:27)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.b.b.b.a(SourceFile:400)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.b.b.b.b(SourceFile:177)
[23:09:48 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[23:09:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:09:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:09:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:611)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:448)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:518)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.fireExtinguished(BlockFireAbstract.java:120)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:71)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFire.onPlace(BlockFire.java:348)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:56)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.onPlace(BlockBase.java:550)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:521)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:395)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeUpdate(World.java:557)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.FluidTypeLava.b(FluidTypeLava.java:49)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.Fluid.b(SourceFile:84)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFluids.tick(BlockFluids.java:41)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:562)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:851)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:827)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:744)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:09:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:09:48 WARN]: Caused by: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
[23:09:48 WARN]:        at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:158)
[23:09:48 WARN]:        at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:57)
[23:09:48 WARN]:        ... 43 more
[23:09:48 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[23:09:48 WARN]:        at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
[23:09:48 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:09:48 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[23:09:48 WARN]:        at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:156)
[23:09:48 WARN]:        ... 44 more
[23:09:48 WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[23:09:48 WARN]:        at java.util.zip.InflaterInputStream.fill(Unknown Source)
[23:09:48 WARN]:        at java.util.zip.InflaterInputStream.read(Unknown Source)
[23:09:48 WARN]:        at java.util.zip.GZIPInputStream.read(Unknown Source)
[23:09:48 WARN]:        at java.io.BufferedInputStream.fill(Unknown Source)
[23:09:48 WARN]:        at java.io.BufferedInputStream.read(Unknown Source)
[23:09:48 WARN]:        at java.io.DataInputStream.readByte(Unknown Source)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:168)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:145)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:58)
[23:09:48 WARN]:        ... 48 more
[23:09:48 ERROR]: [ItemsAdder] Error moving corrupted region to 'corrupted_data' folder
[23:09:48 WARN]: java.io.IOException: Failed to delete original file 'F:\Minecraft\plugins\ItemsAdder\storage\regions_data\world\r.1.0.nbt' after copy to 'F:\Minecraft\plugins\ItemsAdder\storage\regions_data\corrupted_data\world\r.1.0.nbt'
[23:09:48 WARN]:        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:3011)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.d.b(SourceFile:109)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.c.b.a(SourceFile:27)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.b.b.b.a(SourceFile:400)
[23:09:48 WARN]:        at dev.lone.itemsadder.e.e.a.b.b.b.b(SourceFile:177)
[23:09:48 WARN]:        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[23:09:48 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[23:09:48 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[23:09:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:611)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:448)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:518)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.fireExtinguished(BlockFireAbstract.java:120)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:71)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFire.onPlace(BlockFire.java:348)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:56)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.onPlace(BlockBase.java:550)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:521)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.a(World.java:395)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.World.setTypeUpdate(World.java:557)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.FluidTypeLava.b(FluidTypeLava.java:49)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.Fluid.b(SourceFile:84)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockFluids.tick(BlockFluids.java:41)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:562)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:851)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:827)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:744)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[23:09:48 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:09:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:09:48 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.0.48
java.lang.NullPointerException: null
        at dev.lone.itemsadder.e.e.a.b.b.b.a(SourceFile:401) ~[?:?]
        at dev.lone.itemsadder.e.e.a.b.b.b.b(SourceFile:177) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-202]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-202]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.a(World.java:611) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.a(World.java:448) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.a(World.java:518) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockFireAbstract.fireExtinguished(BlockFireAbstract.java:120) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:71) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockFire.onPlace(BlockFire.java:348) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:56) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.onPlace(BlockBase.java:550) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:521) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.a(World.java:395) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.World.setTypeUpdate(World.java:557) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.FluidTypeLava.b(FluidTypeLava.java:49) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.Fluid.b(SourceFile:84) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockFluids.tick(BlockFluids.java:41) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:562) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:851) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:827) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:744) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-202]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-202]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[23:09:48 INFO]: Saved file: F:\Minecraft\plugins\ItemsAdder\storage\regions_data\world\r.1.0.nbt
[23:09:48 INFO]: [ItemsAdder] All worlds: saved 1 regions
[23:09:51 INFO]: [ItemsAdder]     Found cached default resourcepack`

**Comment by LoneDev6** [comment]
Will be fixed in next update, thanks
