### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Henaminator** [LoneDev6/ItemsAdder#402]
**Describe the bug**
[17:46:02] [Craft Scheduler Thread - 47/INFO]: [ItemsAdder] world_nether: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 55/INFO]: [ItemsAdder] world: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 56/INFO]: [ItemsAdder] world: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 54/INFO]: [ItemsAdder] world_nether: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 53/INFO]: [ItemsAdder] Resource: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 49/INFO]: [ItemsAdder] Resource: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 42/INFO]: [ItemsAdder] Resource_nether: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 51/INFO]: [ItemsAdder] Resource_nether: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 51/INFO]: [ItemsAdder] Spawn: saved 0 regions
[17:46:02] [Craft Scheduler Thread - 57/INFO]: [ItemsAdder] Spawn: saved 0 regions
[17:50:02] [Server thread/WARN]: java.lang.IllegalThreadStateException: InitializationException
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.e.f.class.a(a:515)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.j.b.a.class.a(a:362)
[17:50:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:50:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:50:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:50:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.f.j.b.c.class.a(a:890)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.l.b.f.f.class.a(a:587)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.l.b.b.b.class.a(a:13)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.k.a.class.a(a:7)
[17:50:02] [Server thread/WARN]: 	at dev.lone.itemsadder.c.b.class.a(a:164)
[17:50:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[17:50:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[17:50:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[17:50:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[17:50:02] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:50:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[17:50:02] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.0
[17:50:02] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[17:50:02] [Server thread/INFO]: [ItemsAdder] All worlds: saved 0 regions
[17:50:02] [Craft Scheduler Thread - 7/INFO]: java.net.SocketException: Socket closed
[17:50:02] [Server thread/INFO]: [ItemsAdder] Saved 0 player stats files
[17:50:02] [Server thread/INFO]: [ItemsAdder] Saving custom entities...
[17:50:02] [Server thread/INFO]: [ItemsAdder] Saved 0 custom entities successfully!
[17:51:02] [Craft Scheduler Thread - 53/INFO]: [LibsDisguises] Now looking for update on Github..
[18:01:48] [Server thread/INFO]: xSorch issued server command: /ia
[18:01:48] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ia' in plugin ItemsAdder v2.1.0 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.3.jar:git-Paper-208]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-208]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-208]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-208]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**To Reproduce**
Just happens randomly after the recent plugin update, everything works fine for a minute and the next it doesn't without me having touched anything.

**Info (please complete the following information):**
 - Server version: Paper 1.16.3
 - Client version: 1.16.3 Regular
 - Plugin version: 2.1.0

**Comment by LoneDev6** [comment]
Duplicate, let's discuss here https://github.com/LoneDev6/ItemsAdder/issues/404
