### ISSUE TITLE
[BUG] ItemsAdder autodisabled

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#408]
**Describe the bug**
[14:08:02]: [WARN] java.lang.IllegalThreadStateException: InitializationException
[14:08:02]: [WARN] at dev.lone.itemsadder.b.k.class.a(a:501)
[14:08:02]: [WARN] at dev.lone.itemsadder.f.f.a.b.b.h.class.a(a:298)
[14:08:02]: [WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:08:02]: [WARN] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:08:02]: [WARN] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:08:02]: [WARN] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[14:08:02]: [WARN] at dev.lone.itemsadder.f.f.c.c.class.a(a:757)
[14:08:02]: [WARN] at dev.lone.itemsadder.f.f.a.b.b.m.class.a(a:183)
[14:08:02]: [WARN] at dev.lone.itemsadder.c.q.class.a(a:913)
[14:08:02]: [WARN] at dev.lone.itemsadder.f.f.c.a.r.class.a(a:121)
[14:08:02]: [WARN] at dev.lone.itemsadder.e.i.class.a(a:865)
[14:08:02]: [WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:08:02]: [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[14:08:02]: [WARN] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[14:08:02]: [WARN] at java.base/java.lang.Thread.run(Thread.java:834)
[14:08:02]: [INFO] [ItemsAdder] Disabling ItemsAdder v2.1.1
[14:08:02]: [INFO] [ItemsAdder] All worlds: saved 0 regions
[14:08:02]: [INFO] [ItemsAdder] All worlds: saved 0 regions
[14:08:02]: [INFO] [ItemsAdder] Saved 0 player stats files
[14:08:02]: [INFO] [ItemsAdder] Saving custom entities...
[14:08:02]: [INFO] [ItemsAdder] Saved 0 custom entities successfully!

**To Reproduce**
Ciao Matteo, il server è aperto da questa mattina... e nessuno è presente all'interno del server. Io ho finito di pranzare ora e tornando alla console (senza accedere al server con il mio personaggio) ho trovato questo errore in rosso.
Mi sembra strano che si autodisabiliti...

Modificato per aggiungere: succede frequentemente, ma impossibile prevedere in che momento. Sto all'interno del server appunto senza fare assolutamente nulla e d'un tratto, si disabilità mostrando queste linee di codice.

Se può aiutarti, ho creato un timings:
https://timings.aikar.co/?id=ffb2c09be5684cb4b221e7f977f0ac54

e ho anche creato un link ai log della console dove puoi controllare tutto fino alla fine dove avviene la disabilitazione:
https://log.mtxserv.com/w9MAAa2

**Comment by Fargus5** [comment]
If this can help you...
[https://timings.aikar.co/?id=ffb2c09be5684cb4b221e7f977f0ac54](url)

**Comment by LoneDev6** [comment]
Ho già corretto questo problema nell'ultimo aggiornamento, ti invito ad aggiornare a 2.1.2
