### ISSUE TITLE
[BUG] Some Wrong on Plugin Loading

### ISSUE THREAD

**Issue by dabai233** [LoneDev6/ItemsAdder#412]
**Describe the bug**
[02:39:03 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[02:39:03 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R2.block.data.CraftBlockData cannot be cast to org.bukkit.block.data.MultipleFacing
[02:39:03 WARN]: at dev.lone.itemsadder.f.e.a.b.<init>(SourceFile:30)
[02:39:03 WARN]: at dev.lone.itemsadder.f.e.d.<init>(SourceFile:67)
[02:39:03 WARN]: at dev.lone.itemsadder.f.b.g(SourceFile:533)
[02:39:03 WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:339)
[02:39:03 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:101)
[02:39:03 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[02:39:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1368)
[02:39:03 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:391)
[02:39:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278)
[02:39:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009)
[02:39:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[02:39:03 WARN]: at java.lang.Thread.run(Unknown Source)

**To Reproduce**
1. Just Start The Server or Reload The Plugin

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: Paper 1.16.3
 - Client version: 1.16.3
 - Plugin version: 2.1.2

**Additional context**
I just upgraded the plug-in from 2.0.47 to 2.1.2, and then the plug-in had these errors

**Comment by dabai233** [comment]
The problem is solved! It's blockus addon!
After I deleted blockus, the plug-in is back to work!
Sorry for taking up your working time

**Comment by LoneDev6** [comment]
Please read here in order to fix the issue: https://github.com/LoneDev6/ItemsAdder/issues/186#issuecomment-621268971
