### ISSUE TITLE
Mythicmobs items drop

### ISSUE THREAD

**Issue by WhiteProject1** [LoneDev6/ItemsAdder#4205]
### Terms

- [X] I'm using the very latest version of ItemsAdder and its dependencies.
- [X] I am sure this is a bug and it is not caused by a misconfiguration or by another plugin.
- [X] I've looked for already existing issues on the [Issue Tracker](https://github.com/PluginBugs/Issues-ItemsAdder/issues) and haven't found any.
- [X] I already searched on the [plugin wiki](https://itemsadder.devs.beer/) to know if a solution is already known.
- [X] I already searched on the [forums](https://forum.devs.beer/) to check if anyone already has a solution for this.
- [X] I tested this with just ItemsAdder and its dependencies and with a vanilla client of the same version as the Server.

### Discord Username (optional)

batuhan____

### What happened?

mythicmobs config give error drop item

### Steps to reproduce the issue

JUST KİLL MOB

### Server version

[04:57:18 INFO]: §7This server is running §b§lLight Spigot§7. [1.20.4]

Previous version: git-Purpur-1171 (MC: 1.16.5)

### ItemsAdder Version

ItemsAdder version 3.6.6-legacy

### ProtocolLib Version

 ProtocolLib version 5.3.0

### LoneLibs Version

LoneLibs version 1.0.61

### Full Server Log

https://mclo.gs/3jPFVfH

### Error (optional)

```shell
[MythicMobs] [EVENTS] Exception thrown whilst handling event: org.bukkit.event.entity.EntityDeathEvent
[03:55:58] [Server thread/WARN]: java.lang.InstantiationError: io.lumine.mythic.bukkit.adapters.BukkitItemStack
[03:55:58] [Server thread/WARN]: 	at ItemsAdder_3.6.6-legacy.jar//dev.lone.itemsadder.Core.OtherPlugins.MythicMobs.drops.CustomItemDrop.getDrop(SourceFile:28)
[03:55:58] [Server thread/WARN]: 	at MythicMobs-5.7.2.jar//io.lumine.mythic.core.drops.DropExecutor.handleEntityLootDrops(DropExecutor.java:315)
[03:55:58] [Server thread/WARN]: 	at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.adapters.BukkitSkillTriggers.onDeathTrigger(BukkitSkillTriggers.java:423)
[03:55:58] [Server thread/WARN]: 	at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144)
[03:55:58] [Server thread/WARN]: 	at MythicMobs-5.7.2.jar//io.lumine.mythic.bukkit.utils.events.functional.single.EventListener.execute(EventListener.java:131)
[03:55:58] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[03:55:58] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[03:55:58] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[03:55:58] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[03:55:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[03:55:58] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:987)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1871)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1765)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1589)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:319)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1336)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2286)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2791)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2715)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.a(PlayerConnectionUtils.java:54)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1478)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1455)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1378)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bu(IAsyncTaskHandler.java:112)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1570)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1233)
[03:55:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[03:55:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[03:55:58] [Server thread/INFO]: Named entity EntityZombie['Zombie'/1462, uuid='d4d8230f-7b92-4610-afda-d20f184fbd88', l='ServerLevel[zindan]', x=146.30, y=149.00, z=-4.30, cpos=[9, -1], tl=359, v=true] died: Zombie was slain by _BatuhanDEV_
[03:56:08] [Server thread/INFO]: _BatuhanDEV_ issued server command: /mm reload
```

### Screenshots/Videos (you can drag and drop files or paste links)

![image](https://github.com/user-attachments/assets/d4e20f73-cbcb-4bd7-905d-b2d5ede55fe0)

**Comment by WhiteProject1** [comment]
I tryed on offical paper verison to but dont work
