### ISSUE TITLE
[BUG] IA crashing the server

### ISSUE THREAD

**Issue by LoganTheOverlord** [LoneDev6/ItemsAdder#438]
**Describe the bug**
ItemsAdder is crashing server while generating world.
**To Reproduce**
1. Go to 'Generate world as you would normally do by flying around'

**Expected behavior**
No crash

**Screenshots**
[15:28:19 ERROR]: [ItemsAdder] Corrupted region data! Moving it into 'corrupted_data' folder: tezba/r.2.-4.nbt
[15:28:19 WARN]: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
[15:28:19 WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:59)
[15:28:19 WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTFile.<init>(NBTFile.java:36)
[15:28:19 WARN]: at dev.lone.itemsadder.f.f.a.c.b.b.<init>(SourceFile:23)
[15:28:19 WARN]: at dev.lone.itemsadder.f.f.a.c.b.a.<init>(SourceFile:22)
[15:28:19 WARN]: at dev.lone.itemsadder.f.f.a.c.d.b(SourceFile:107)
[15:28:19 WARN]: at dev.lone.itemsadder.f.f.a.c.b.c(SourceFile:29)
[15:28:19 WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:2008)
[15:28:19 WARN]: at dev.lone.itemsadder.f.e.d.a(SourceFile:157)
[15:28:19 WARN]: at dev.lone.itemsadder.f.e.d.a(SourceFile:95)
[15:28:19 WARN]: at dev.lone.itemsadder.f.e.d.a(SourceFile:90)
[15:28:19 WARN]: at dev.lone.itemsadder.f.k.c.a(SourceFile:154)
[15:28:19 WARN]: at dev.lone.itemsadder.f.k.c.populate(SourceFile:89)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.Chunk.loadCallback(Chunk.java:877)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$14(PlayerChunk.java:772)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:137)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1236)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.ExecServ_.flush(ExecServ_.java:128)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.ExecServ_.flushAndShutdown(ExecServ_.java:154)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1421)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1257)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:983)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:164)
[15:28:19 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:28:19 WARN]: Caused by: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
[15:28:19 WARN]: at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:158)
[15:28:19 WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:57)
[15:28:19 WARN]: ... 24 more
[15:28:19 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[15:28:19 WARN]: at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
[15:28:19 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:28:19 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[15:28:19 WARN]: at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:156)
[15:28:19 WARN]: ... 25 more
[15:28:19 WARN]: Caused by: net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:176)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:145)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:58)
[15:28:19 WARN]: ... 29 more
[15:28:19 WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[15:28:19 WARN]: at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
[15:28:19 WARN]: at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[15:28:19 WARN]: at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[15:28:19 WARN]: at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[15:28:19 WARN]: at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[15:28:19 WARN]: at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[15:28:19 WARN]: at java.io.DataInputStream.readFully(DataInputStream.java:195)
[15:28:19 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:609)
[15:28:19 WARN]: at java.io.DataInputStream.readUTF(DataInputStream.java:564)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.d(NBTTagCompound.java:456)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.access$100(NBTTagCompound.java:27)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:50)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:28:19 WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:461)
[15:28:19 WARN]: ... 35 more
[15:28:19 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
at dev.lone.itemsadder.f.e.d.a(SourceFile:158) ~[?:?]
at dev.lone.itemsadder.f.e.d.a(SourceFile:95) ~[?:?]
at dev.lone.itemsadder.f.e.d.a(SourceFile:90) ~[?:?]
at dev.lone.itemsadder.f.k.c.a(SourceFile:154) ~[?:?]
at dev.lone.itemsadder.f.k.c.populate(SourceFile:89) ~[?:?]
at net.minecraft.server.v1_16_R2.Chunk.loadCallback(Chunk.java:877) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$14(PlayerChunk.java:772) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:137) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1236) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.ExecServ_.flush(ExecServ_.java:128) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.ExecServ_.flushAndShutdown(ExecServ_.java:154) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1421) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1257) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:983) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:164) ~[ssspigot807868884815929765.jar:SSSpigot-1.16.3-20200915-15496ba]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
[15:28:19 ERROR]: This crash report has been saved to: /hlserver/27387/./crash-reports/crash-2020-10-21_15.28.19-server.txt

**Info (please complete the following information):**
 - Server version: SSSpigot 1.16.3 (Custom spigot fork, may send you both launcher and bin/jar for you to test out)
 - Client version: Optifine 1.16.3
 - Plugin version: 2.1.10

**Additional context**
None

**Comment by LoneDev6** [comment]
Can you test the plugin on original Spigot server?
Let me know if it crashes. If it doesn't crash it's a problem of the fork.

You should also make sure if you installed the latest LoneLibs update

**Comment by 100petr** [comment]
#444
