### ISSUE TITLE
[BUG] crash

### ISSUE THREAD

**Issue by pooooob** [LoneDev6/ItemsAdder#439]
**Describe the bug**
crash every 40 minutes

**To Reproduce**

**Expected behavior**
crash

**Screenshots**
[22:14:41 INFO]: Done (19.917s)! For help, type "help"
[22:14:41 INFO]: Timings Reset
[22:14:43 INFO]: [ItemsAdder]     Downloading default resourcepack...
[22:14:44 INFO]: -------< LightAPI-fork 3.4.5 >-------
[22:14:44 INFO]: You are running the latest version!
> PL
[22:14:48 INFO]: Plugins (4): ItemsAdder, LightAPI, LoneLibs, ProtocolLib
[22:16:04 INFO]: [ItemsAdder]     Downloaded default resourcepack
[22:16:04 INFO]: [ItemsAdder]     Extracting resources from default resourcepack
[22:16:24 INFO]: [ItemsAdder]         DONE extracting resources from default resourcepack
[22:16:24 INFO]: [ItemsAdder]     Extracting default items from .jar
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/vehicles.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/armors.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/crops.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/realcraft/huds_images.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/guns.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/magiccraft/huds.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/realcraft/huds.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_categories/en.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/mcemojis/emoji_images.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/magiccraft/huds_images.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/example/example_items.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_categories/tr.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/mcguis/mcguis.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/totems_of_undying.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/it.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/bows.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/vegetables_and_fruits.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/tools.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/es.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/mcicons/icons.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/example/images_tags.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_categories/it.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/fishing_rods.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/zh_cn.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/tr.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/items.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/food.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/realcraft/water.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/blocks.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/swords.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/en.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/throwables.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_items/fr.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/gui.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/minerals.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/drinks.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/books.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/shields.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/dictionaries/ia_default_categories/zh_cn.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/various_configs/ia_gui_default_categories.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/hats.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/itemsadder/furnitures.yml
[22:16:24 INFO]: [ItemsAdder]        - Extracted data/items_packs/twitteremojis/emoji_images.yml
[22:16:24 INFO]: [ItemsAdder]       DONE extracting default items from .jar
[22:16:27 INFO]: [ItemsAdder] Used 568/6608 available max font images.
[22:16:28 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[22:16:28 INFO]: [ItemsAdder] Loaded 484 items
[22:16:28 INFO]: [ItemsAdder] Used 26/191 REAL block IDs.
[22:16:28 INFO]: [ItemsAdder] Used 0/63 REAL_TRANSPARENT block IDs.
[22:16:28 INFO]: [ItemsAdder] Checking resourcepack url... http://matteodev.it/spigot/itemsadder/res/v2/precompressed/precompressed_example_pack.zip
[22:16:28 INFO]: [ItemsAdder] Loaded 40 categories
[22:16:28 INFO]: [ItemsAdder] Loaded items and stuff in 4329ms
[22:16:30 INFO]: [ItemsAdder] Compressing resource_pack ...
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:32 INFO]: [ItemsAdder]     Resource pack successfully compressed. Get the file here: plugins\ItemsAdder\data\resource_pack\pack.zip
[22:16:32 INFO]: [ItemsAdder] And follow this tutorial before asking for support: https://itemsadder.plugin.ga/plugin-usage/resourcepack-hosting/resourcepack-on-dropbox
[22:16:32 INFO]: [ItemsAdder] Checking resourcepack url... http://matteodev.it/spigot/itemsadder/res/v2/precompressed/precompressed_example_pack.zip
[22:16:32 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:33 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:33 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:33 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
> w
[22:16:33 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:33 INFO]: Unknown command
[22:16:33 INFO]: w<--[HERE]
[22:16:34 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:34 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
> e
[22:16:34 WARN]: [ItemsAdder] You cannot execute this from console! Use this command ingame
[22:16:34 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[22:16:34 INFO]: [ItemsAdder]     Resourcepack URL is valid. Type: application/zip
[23:02:42 WARN]: java.lang.IllegalThreadStateException: InitializationException
[23:02:42 WARN]:        at dev.lone.itemsadder.i.i.class.a(a:782)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.f.c.b.f.class.a(a:544)
[23:02:42 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:02:42 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[23:02:42 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:02:42 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.f.a.b.b.a.d.class.a(a:385)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.f.a.f.class.a(a:51)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.f.a.c.class.a(a:442)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.f.c.c.class.a(a:272)
[23:02:42 WARN]:        at dev.lone.itemsadder.f.h.a.b.class.a(a:55)
[23:02:42 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[23:02:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:02:42 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:02:42 WARN]:        at java.lang.Thread.run(Unknown Source)
[23:02:42 INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.8

**Info (please complete the following information):**
 - Server version: paper 1.15.2
 - Client version: vanilla 1.15.2
 - Plugin version: 2.1.8

**Additional context**

**Comment by LoneDev6** [comment]
Please contact me via PM on SpigotMC.org, thanks
