### ISSUE TITLE
[BUG] Could not pass event BlockPhysicsEvent to ItemsAdder v2.1.10

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#444]
Ciao, sto avendo questo errore nella console, ma non riesco a riprodurlo manualmente per capire in quale condizione si riproduce.

https://log.mtxserv.com/Ejkw2mR#L1958

```

[22:00:59] [Server thread/ERROR]: [ItemsAdder] Corrupted region data! Moving it into 'corrupted_data' folder: world/r.-1.18.nbt
--
1882 | [22:00:59] [Server thread/WARN]: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
1883 | [22:00:59] [Server thread/WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:59)
1884 | [22:00:59] [Server thread/WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTFile.<init>(NBTFile.java:36)
1885 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.c.b.b.<init>(SourceFile:23)
1886 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.c.b.a.<init>(SourceFile:22)
1887 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.c.d.b(SourceFile:107)
1888 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.c.b.c(SourceFile:29)
1889 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:2008)
1890 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:141)
1891 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:228)
1892 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:414)
1893 | [22:00:59] [Server thread/WARN]: at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:354)
1894 | [22:00:59] [Server thread/WARN]: at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
1895 | [22:00:59] [Server thread/WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
1896 | [22:00:59] [Server thread/WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
1897 | [22:00:59] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
1898 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.a(World.java:611)
1899 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566)
1900 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183)
1901 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481)
1902 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.a(World.java:448)
1903 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
1904 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.World.a(World.java:518)
1905 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:367)
1906 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283)
1907 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:249)
1908 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1395)
1909 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40)
1910 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10)
1911 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
1912 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
1913 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
1914 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
1915 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
1916 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
1917 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
1918 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
1919 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202)
1920 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
1921 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
1922 | [22:00:59] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
1923 | [22:00:59] [Server thread/WARN]: Caused by: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
1924 | [22:00:59] [Server thread/WARN]: at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:158)
1925 | [22:00:59] [Server thread/WARN]: at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:57)
1926 | [22:00:59] [Server thread/WARN]: ... 39 more
1927 | [22:00:59] [Server thread/WARN]: Caused by: java.lang.reflect.InvocationTargetException
1928 | [22:00:59] [Server thread/WARN]: at jdk.internal.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
1929 | [22:00:59] [Server thread/WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
1930 | [22:00:59] [Server thread/WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:566)
1931 | [22:00:59] [Server thread/WARN]: at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:156)
1932 | [22:00:59] [Server thread/WARN]: ... 40 more
1933 | [22:00:59] [Server thread/WARN]: Caused by: net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
1934 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:475)
1935 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
1936 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
1937 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
1938 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:176)
1939 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:145)
1940 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:58)
1941 | [22:00:59] [Server thread/WARN]: ... 44 more
1942 | [22:00:59] [Server thread/WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
1943 | [22:00:59] [Server thread/WARN]: at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
1944 | [22:00:59] [Server thread/WARN]: at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
1945 | [22:00:59] [Server thread/WARN]: at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
1946 | [22:00:59] [Server thread/WARN]: at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
1947 | [22:00:59] [Server thread/WARN]: at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
1948 | [22:00:59] [Server thread/WARN]: at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
1949 | [22:00:59] [Server thread/WARN]: at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
1950 | [22:00:59] [Server thread/WARN]: at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
1951 | [22:00:59] [Server thread/WARN]: at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
1952 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.d(NBTTagCompound.java:463)
1953 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.access$100(NBTTagCompound.java:27)
1954 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:50)
1955 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
1956 | [22:00:59] [Server thread/WARN]: at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
1957 | [22:00:59] [Server thread/WARN]: ... 50 more
1958 | [22:00:59] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.1.10
1959 | java.lang.NullPointerException: null
1960 | at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:144) ~[?:?]
1961 | at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:228) ~[?:?]
1962 | at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:414) ~[?:?]
1963 | at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:354) ~[?:?]
1964 | at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-244]
1965 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-244]
1966 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-244]
1967 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-244]
1968 | at net.minecraft.server.v1_16_R2.World.a(World.java:611) ~[patched_1.16.3.jar:git-Paper-244]
1969 | at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566) ~[patched_1.16.3.jar:git-Paper-244]
1970 | at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183) ~[patched_1.16.3.jar:git-Paper-244]
1971 | at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481) ~[patched_1.16.3.jar:git-Paper-244]
1972 | at net.minecraft.server.v1_16_R2.World.a(World.java:448) ~[patched_1.16.3.jar:git-Paper-244]
1973 | at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-244]
1974 | at net.minecraft.server.v1_16_R2.World.a(World.java:518) ~[patched_1.16.3.jar:git-Paper-244]
1975 | at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:367) ~[patched_1.16.3.jar:git-Paper-244]
1976 | at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-244]
1977 | at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:249) ~[patched_1.16.3.jar:git-Paper-244]
1978 | at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1395) ~[patched_1.16.3.jar:git-Paper-244]
1979 | at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-244]
1980 | at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-244]
1981 | at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-244]
1982 | at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-244]
1983 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-244]
1984 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-244]
1985 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-244]
1986 | at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-244]
1987 | at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-244]
1988 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-244]
1989 | at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.16.3.jar:git-Paper-244]
1990 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-244]
1991 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-244]
1992 | at java.lang.Thread.run(Thread.java:834) [?:?]


```

Possibile collegamento con questa situazione?
https://github.com/DevLan-Support/tickets/issues/5

**Comment by 100petr** [comment]
The same problem. IA 2.1.10, tuinity 1.16.3. I also wrote to you (lonedev) on spigot. https://pastebin.com/kkGc7bKA  https://pastebin.com/GfzL7HNb

**Comment by LoneDev6** [comment]
@Fargus5 error is about a corrupted region file which could be caused by a bug I have to find.
"Java.io.EOFException: Unexpected end of ZLIB input stream"

While @100petr has a similar error "Caused by: java.io.EOFException" that should mean it's a corrupted file too.


@100petr reported to have had a crash recently which probably corrupted the region file
@Fargus5  ti è crashato il server recentemente? Magari legato a ItemsAdder, potrebbe aver corrotto il file region in questione

**Comment by LoneDev6** [comment]
Can you guys send me your corrupted region files?

**Comment by Fargus5** [comment]
@LoneDev6 no il server non ha subito crash. Ma queste regions corrotte potrebbero forse essere ricollegate al problema degli ore che si trasformano in mushrooms?

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 no il server non ha subito crash. Ma queste regions corrotte potrebbero forse essere ricollegate al problema degli ore che si trasformano in mushrooms?

certamente, dato che itemsadder non carica il region file gli ori non sono più riconosciuti.

devo capire la causa di questi file corrotti perché è troppo strano, sembra che capiti solo dalla 2.1.10 ma boh.. eppure non ho cambiato nulla nel sistema di salvataggio di questi file

**Comment by 100petr** [comment]
And where can I find those corrupted region?
![image](https://user-images.githubusercontent.com/29830635/97162716-df535d00-177f-11eb-98cd-666972030319.png)
![image](https://user-images.githubusercontent.com/29830635/97162756-ee3a0f80-177f-11eb-914b-87ce504a3f98.png)

**Comment by Fargus5** [comment]
> > 
> > 
> > @LoneDev6 no il server non ha subito crash. Ma queste regions corrotte potrebbero forse essere ricollegate al problema degli ore che si trasformano in mushrooms?
> 
> certamente, dato che itemsadder non carica il region file gli ori non sono più riconosciuti.
> 
> devo capire la causa di questi file corrotti perché è troppo strano, sembra che capiti solo dalla 2.1.10 ma boh.. eppure non ho cambiato nulla nel sistema di salvataggio di questi file

Non dimenticare che paper e spigot hanno aggiornato moltissimo. Non so se è correlato'. Ma se può aiutarti...

**Comment by LoneDev6** [comment]
plugins\ItemsAdder\storage\regions_data\tezba\r.-12.-4.nbt


But I think I MAY have found the issue and I'm currently fixing it, but sadly I won't be able to recoder your corrupted regions as they are.. corrupted.
You may restore them from a previous server backup.


Anyway it's a good idea to create a "mining" world as I did on my personal server, so everytime I want to change ores amount or corruption happens (should not, but may happen like in this case) I can just reset the world and regen it

**Comment by 100petr** [comment]
Yes, tezba is mining, but ore are well in the normal world. And I can't give players a few days old backup on the server 
[corrupted_data.zip](https://github.com/LoneDev6/ItemsAdder/files/5438392/corrupted_data.zip)

**Comment by LoneDev6** [comment]
No i mean you can try to stop the server, copy and paste the old itemadder region file that got corrupted, it's r.-12.-4.nbt, then start the server.
it should fix the ores

**Comment by 100petr** [comment]
ah so, well, if it doesn't crash, I don't care :D

**Comment by LoneDev6** [comment]
Lol XD

**Comment by LoneDev6** [comment]
I will publish an update today

**Comment by Fargus5** [comment]
> I will publish an update today

scusami un secondo Matté... ma con questo update quindi cosa vai a fixare di preciso? cioé io dal mio lato mi sembra di aver capito che devo andare a toccare qualcosa nei file ? oppure con l'update dovrebbe fixarsi il problema degli ore?

**Comment by LoneDev6** [comment]
Non si corromperanno più i region file.
L'unico problema è che i region file già corrotti rimarranno così.
L'unico modo per recuperarli è:
- spegnere il server
- ripristinare i file sotto plugins\ItemsAdder\storage\regions_data prendendoli da un backup del server che spero tu abbia, magari di una settimana fa.
- eliminare il vecchio jar di itemadder
- mettere il jar nuovo nuovo nonappena lo pubblicherò
- avviare il server

Fatto ciò dovresti aver sistemato gli ori già generati.

**Comment by Fargus5** [comment]
@LoneDev6 

```

[16:39:34] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.1.11 (Is it up to date?)
--
1003 | java.lang.NullPointerException: null
1004 | at dev.lone.itemsadder.f.f.a.c.d.c(SourceFile:82) ~[?:?]
1005 | at dev.lone.itemsadder.f.f.a.c.d.<init>(SourceFile:43) ~[?:?]
1006 | at dev.lone.itemsadder.f.f.a.c.b.<init>(SourceFile:18) ~[?:?]
1007 | at dev.lone.itemsadder.f.b.b(SourceFile:263) ~[?:?]
1008 | at dev.lone.itemsadder.f.b.<init>(SourceFile:199) ~[?:?]
1009 | at dev.lone.itemsadder.Main.onEnable(SourceFile:183) ~[?:?]
1010 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-246]
1011 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-246]
1012 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
1013 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
1014 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
1015 | at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-246]
1016 | at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-246]
1017 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
1018 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
1019 | at java.lang.Thread.run(Thread.java:834) [?:?]
1020 | [16:39:34] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.11
1021 | [16:39:34] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v2.1.11 (Is it up to date?)
1022 | java.lang.IllegalArgumentException: listener cannot be NULL
1023 | at com.comphenix.protocol.injector.PacketFilterManager.removePacketListener(PacketFilterManager.java:462) ~[?:?]
1024 | at dev.lone.itemsadder.f.f.a.b.m.E(SourceFile:471) ~[?:?]
1025 | at dev.lone.itemsadder.Main.onDisable(SourceFile:272) ~[?:?]
1026 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-246]
1027 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-246]
1028 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-246]
1029 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-246]
1030 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-246]
1031 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-246]
1032 | at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-246]
1033 | at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-246]
1034 | at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-246]
1035 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-246]
1036 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]


```
