### ISSUE TITLE
[BUG] SWAP_ITEM_WITH_OFFHAND Console error

### ISSUE THREAD

**Issue by GreenTree0** [LoneDev6/ItemsAdder#445]
**Describe the bug**
Each time a player swap an item with his offhand it calls an error in the console (in 1.16.3, no other plugins installed).

Here is the error : 
`[ItemsAdder] Unhandled exception occured in onPacketReceiving(PacketEvent) for ItemsAdder
java.lang.IllegalArgumentException: No enum constant com.comphenix.protocol.wrappers.EnumWrappers.PlayerDigType.SWAP_ITEM_WITH_OFFHAND
at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_262]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:695) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.wrappers.EnumWrappers$EnumConverter.getSpecific(EnumWrappers.java:684) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[ProtocolLib.jar:4.5.1]
at dev.lone.itemsadder.f.f.a.b.b.b.d.onPacketReceiving(SourceFile:94) ~[ItemsAdder.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:350) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:315) [ProtocolLib.jar:4.5.1]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:538) [ProtocolLib.jar:4.5.1]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) [ProtocolLib.jar:4.5.1]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.16.3.jar:git-Spigot-57bbdd8-b8dd5ec]
at java.lang.Thread.run(Thread.java:748) `[?:1.8.0_262]`

**To Reproduce**
Setup an 1.16.3 with ItemsAdder and his dependencies.
Change an item with your offhand.

**Expected behavior**
Well I just don't wan't errors popping forever in my console.

**Screenshots**
Not necessary.

**Info (please complete the following information):**
 - Server version: Spigot 1.16.3
 - Client version: Normal 1.16.3
 - Plugin version: 2.1.10

**Additional context**

**Comment by 100petr** [comment]
Same issue tuinity 1.16.3 ia 2.1.10 https://pastebin.com/Zgv4SR4x

**Comment by LoneDev6** [comment]
Did you try to update protocollib? https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by 100petr** [comment]
I have this version of protocollib and I got the error too. But I'll try the b482 again
![image](https://user-images.githubusercontent.com/29830635/97212808-29a8fe00-17c1-11eb-9fd6-2c9a1afe67f6.png)
![image](https://user-images.githubusercontent.com/29830635/97212822-2e6db200-17c1-11eb-86a5-9461d5852d51.png)
https://pastebin.com/08dHLM3h

**Comment by 100petr** [comment]
Still https://pastebin.com/qDUd4KZA

**Comment by LoneDev6** [comment]
this is not the full log, it has only part of the info

**Comment by GreenTree0** [comment]
Updating protocollib did the trick, ty.
