### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#447]
Non ho idea di cosa sia ma spamma in console:
https://log.mtxserv.com/1Q75sOt

```

[16:22:56] [Craft Scheduler Thread - 181/WARN]: [ItemsAdder] Plugin ItemsAdder v2.1.10 generated an exception while executing task 1084
--
4734 | java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
4735 | at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.3.jar:git-Paper-246]
4736 | at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.3.jar:git-Paper-246]
4737 | at dev.lone.itemsadder.f.f.a.b.b.b.c.f(SourceFile:68) ~[?:?]
4738 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
4739 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-246]
4740 | at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-246]
4741 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
4742 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
4743 | at java.lang.Thread.run(Thread.java:834) [?:?]
4744 | [16:22:59] [Craft Scheduler Thread - 185/WARN]: [ItemsAdder] Plugin ItemsAdder v2.1.10 generated an exception while executing task 1084
4745 | java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
4746 | at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.16.3.jar:git-Paper-246]
4747 | at org.bukkit.Location.distance(Location.java:493) ~[patched_1.16.3.jar:git-Paper-246]
4748 | at dev.lone.itemsadder.f.f.a.b.b.b.c.f(SourceFile:68) ~[?:?]
4749 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
4750 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-246]
4751 | at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-246]
4752 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
4753 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
4754 | at java.lang.Thread.run(Thread.java:834) [?:?]


```

**Comment by 100petr** [comment]
Same problem. ia 2.1.10 tuinity 1.16.3 https://pastebin.com/Tn4Fc90F

**Comment by LoneDev6** [comment]
Will be fixed, thanks

**Comment by 100petr** [comment]
Hi, again - purpur https://pastebin.com/fdst7axN

**Comment by LoneDev6** [comment]
> 
> 
> Hi, again - purpur https://pastebin.com/fdst7axN
> I don't know if this is ia or purple problem.

Will be fixed, thanks
