### ISSUE TITLE
New ItemsAdder not working 1.15.2

### ISSUE THREAD

**Issue by MaciekJRPL** [LoneDev6/ItemsAdder#449]
Hi, I just updated the plugin and it won't turn on
![Screenshot_1](https://user-images.githubusercontent.com/68289732/97182244-98279500-179c-11eb-8dd2-18a95bbcd23c.png)

                                                        
```
[15:07:19] [Server thread/INFO]: [ItemsAdder] Loading data...
[15:07:19] [Server thread/ERROR]: Error occurred while enabling ItemsAdder v2.1.11 (Is it up to date?)
java.lang.NullPointerException: null
	at dev.lone.itemsadder.f.f.a.c.d.c(SourceFile:82) ~[?:?]
	at dev.lone.itemsadder.f.f.a.c.d.<init>(SourceFile:44) ~[?:?]
	at dev.lone.itemsadder.f.f.a.c.b.<init>(SourceFile:18) ~[?:?]
	at dev.lone.itemsadder.f.b.b(SourceFile:263) ~[?:?]
	at dev.lone.itemsadder.f.b.<init>(SourceFile:199) ~[?:?]
	at dev.lone.itemsadder.Main.onEnable(SourceFile:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[15:07:19] [Server thread/INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.11
[15:07:19] [Server thread/ERROR]: Error occurred while disabling ItemsAdder v2.1.11 (Is it up to date?)
java.lang.IllegalArgumentException: listener cannot be NULL
	at com.comphenix.protocol.injector.PacketFilterManager.removePacketListener(PacketFilterManager.java:462) ~[?:?]
	at dev.lone.itemsadder.f.f.a.b.m.E(SourceFile:471) ~[?:?]
	at dev.lone.itemsadder.Main.onDisable(SourceFile:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.15.2.jar:git-Tuinity-"e41b5ce"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

**Comment by Fargus5** [comment]
relation with: https://github.com/LoneDev6/ItemsAdder/issues/444

@LoneDev6 HELP

**Comment by LoneDev6** [comment]
check if you have this folder:
plugins\ItemsAdder\storage\regions_data

if you don't have it or if it's called region_data please create/rename it to regions_data and restart

thanks!
