### ISSUE TITLE
bug addon blockus

### ISSUE THREAD

**Issue by istarengwa** [LoneDev6/ItemsAdder#473]
Hello, I use the version 2.1.15b for itemadders and when I put a block from the blockus module I get an error and just a spawner is displayed

[11:19:31 WARN]: [ItemsAdder] Task #14817 for ItemsAdder v2.1.15 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R2/NBTBase
        at dev.lone.itemsadder.f.e.b.a.<init>(SourceFile:26) ~[?:?]
        at dev.lone.itemsadder.f.e.b.a.a(SourceFile:33) ~[?:?]
        at dev.lone.itemsadder.f.e.b.a.a(SourceFile:39) ~[?:?]
        at dev.lone.itemsadder.f.e.a.b.c(SourceFile:136) ~[?:?]
        at dev.lone.itemsadder.f.e.d.c(SourceFile:151) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Purpur-815]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Purpur-815]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1367) ~[patched_1.16.4.jar:git-Purpur-815]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.4.jar:git-Purpur-815]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1280) ~[patched_1.16.4.jar:git-Purpur-815]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1006) ~[patched_1.16.4.jar:git-Purpur-815]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Purpur-815]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R2.NBTBase
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.4.jar:git-Purpur-815]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.4.jar:git-Purpur-815]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        ... 13 more

when I set the nature of the block to REAL it works correctly.

**Comment by LoneDev6** [comment]
Thanks, fixed in the upcoming update
