### ISSUE TITLE
console ERROR list

### ISSUE THREAD

**Issue by ninesik** [LoneDev6/ItemsAdder#480]
[20:26:59 ERROR]: Could not pass event PlayerJoinEvent to ItemsAdder v2.1.16
java.lang.NullPointerException: null
        at dev.lone.itemsadder.f.i.d.a.a(SourceFile:14) ~[?:?]
        at dev.lone.itemsadder.f.i.d.a.b(SourceFile:21) ~[?:?]
        at dev.lone.itemsadder.h.d.q(SourceFile:268) ~[?:?]
        at dev.lone.itemsadder.h.d.o(SourceFile:252) ~[?:?]
        at dev.lone.itemsadder.h.d.b(SourceFile:236) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-261]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:165) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

[20:26:59 INFO]: NineSik joined the game
[20:26:59 INFO]: NineSik[/122.35.65.68:57781] logged in with entity id 248 at ([world]-284.80517606448325, 49.0, -687.3637437863565)
[20:27:21 WARN]: [ItemsAdder] Task #2847 for ItemsAdder v2.1.16 generated an exception
java.lang.NullPointerException: null
        at dev.lone.itemsadder.f.i.d.a.a(SourceFile:14) ~[?:?]
        at dev.lone.itemsadder.f.i.d.a.b(SourceFile:21) ~[?:?]
        at dev.lone.itemsadder.h.d.q(SourceFile:268) ~[?:?]
        at dev.lone.itemsadder.h.d.ak(SourceFile:220) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

[20:27:37 INFO]: NineSik: 1
[20:27:37 WARN]: [ItemsAdder] Task #7850 for ItemsAdder v2.1.16 generated an exception
java.lang.NullPointerException: null
        at dev.lone.itemsadder.f.i.d.a.a(SourceFile:14) ~[?:?]
        at dev.lone.itemsadder.f.i.d.a.b(SourceFile:21) ~[?:?]
        at dev.lone.itemsadder.h.d.q(SourceFile:268) ~[?:?]
        at dev.lone.itemsadder.h.d.b(SourceFile:427) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

[20:31:21 WARN]: [ItemsAdder] Task #2847 for ItemsAdder v2.1.16 generated an exception
java.lang.NullPointerException: null
        at dev.lone.itemsadder.f.i.d.a.a(SourceFile:14) ~[?:?]
        at dev.lone.itemsadder.f.i.d.a.b(SourceFile:21) ~[?:?]
        at dev.lone.itemsadder.h.d.q(SourceFile:268) ~[?:?]
        at dev.lone.itemsadder.h.d.ak(SourceFile:220) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-261]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-261]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by LoneDev6** [comment]
Please check if you're using the very latest vault update
https://github.com/MilkBowl/Vault/releases/tag/1.7.3
