### ISSUE TITLE
[BUG] Error loading the plugin after update to 1.16

### ISSUE THREAD

**Issue by imparium-de** [LoneDev6/ItemsAdder#486]
**Describe the bug**
After updating from 1.15.2 to 1.16.4, we get an error message in the console

**To Reproduce**
1. Update from 1.15.2 to 1.16.4
2. See error 
[18:45:39 ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
[18:45:39 WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.block.Biome.NETHER
[18:45:39 WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[18:45:39 WARN]: 	at org.bukkit.block.Biome.valueOf(Biome.java:11)
[18:45:39 WARN]: 	at dev.lone.itemsadder.f.d.a.a(SourceFile:207)
[18:45:39 WARN]: 	at dev.lone.itemsadder.f.d.a.m(SourceFile:110)
[18:45:39 WARN]: 	at dev.lone.itemsadder.f.b.a(SourceFile:405)
[18:45:39 WARN]: 	at dev.lone.itemsadder.f.b.a(SourceFile:348)
[18:45:39 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[18:45:39 WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[18:45:39 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297)
[18:45:39 WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[18:45:39 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212)
[18:45:39 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000)
[18:45:39 WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[18:45:39 WARN]: 	at java.lang.Thread.run(Unknown Source)

**Expected behavior**
No errors in console

**Info (please complete the following information):**
 - Server version: paper 1.16.4
 - Client version: Optifine 1.16.4
 - Plugin version: 2.1.15

**Comment by LoneDev6** [comment]
Seems there is a "NETHER" biome set in your configs.
Please check your configs are NETHER biome doesn't exist anymore in 1.16.4.
I suggest you to use Notepad++ to search in items_config directory.
Biomes are here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html

**Comment by imparium-de** [comment]
I completely forgot about that one config, thanks! <3
