### ISSUE TITLE
/ia and /iaemojis not working.

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#488]
Hello !

**Describe the bug** :
I have a problem with commands that open gui and i don't know why.
Context : when i execute /ia, it doesn't work, it doesn't say anything in game (just not openning the gui) and even more, logs don't tell me anything (no logs..).
In addition, when i use /iaemojis, it says "An internal error attempting..... this command". And with /iaemojis, it gives me logs in the console (look  below).
However, all the plugin is working fine, i can get items with /iaget <NAME>, and all others commands are working.

**What's displayed in the console** :
> [09:41:32] [Server thread/INFO]: Valouu issued server command: /ia
> [09:41:35] [Server thread/INFO]: Valouu issued server command: /iaemoji
> [09:41:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'iaemoji' in plugin ItemsAdder v2.0.26
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at dev.lone.itemsadder.d.e.onCommand(SourceFile:35) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
... 17 more

**Version :**
I use the latest spigot version (my server is in 1.15.2).

**More informations :**
The plugin always worked perfectly (i have it for a while now), and i didn't change anything, didn't add items,... so is it maybe a problem with another plugin ? I don't know... 
Thanks for your help,
Valouu.

**Comment by LoneDev6** [comment]
Update the plugin to the latest version.
Also update LoneLibs
