### ISSUE TITLE
[BUG] Could not pass event BlockBreakEvent to ItemsAdder v2.1.18

### ISSUE THREAD

**Issue by SlyJacobTheBeast** [LoneDev6/ItemsAdder#501]
**Describe the bug**
Installed the plugin on local server (local server is a copy of live/hosted server), everything works fine there. Decided to move the plugin to my live server (the same exact server, version everything is same) but after launching it, it gives out following error (no such error appears on the local server):

[Server thread/ERROR]: Could not pass event BlockBreakEvent to ItemsAdder v2.1.18
java.lang.NullPointerException: null
	at dev.lone.itemsadder.f.h.a.f(SourceFile:308) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Paper-259]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-259]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:249) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1469) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1135) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1202) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.4.jar:git-Paper-259]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-259]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Info (please complete the following information):**
 - Server version: PaperMC 1.16.4
 - Client version: Forge 35.0.2
 - Plugin version: 2.1.18

Edit: I just noticed that this issue is the exact same problem. https://github.com/LoneDev6/ItemsAdder/issues/497

**Comment by SlyJacobTheBeast** [comment]
This happened when I copy pasted all the data contents of the plugin from my local server to live server. When I did it properly, it worked fine. Still worth looking at the error I suppose?

**Comment by LoneDev6** [comment]
Answered on the other issue #497
