### ISSUE TITLE
[problem] texture problem

### ISSUE THREAD

**Issue by tlw12344** [LoneDev6/ItemsAdder#506]
hello ive followed the guide to add items and textures ive added a few new items they have loaded in the game fine see screenshot below but the textures are missing ive made sure ive added the correct texture path and all the .json files are there but they are still not loading i have found that when i do /iareload then /iazip the compressing bar just freezes and stays on my screen but my control panel shows no errors ?

screenshot showing the item ingame and that ive added the textures
![image](https://user-images.githubusercontent.com/68190896/99189757-aee95800-275a-11eb-99b0-370094b7a75c.png)
![image](https://user-images.githubusercontent.com/68190896/99189818-1c958400-275b-11eb-9d61-19dd3da11f32.png)
![image](https://user-images.githubusercontent.com/68190896/99189835-3df67000-275b-11eb-8820-75afae1d587a.png)
![image](https://user-images.githubusercontent.com/68190896/99189898-7a29d080-275b-11eb-973b-91959f7b9e21.png)

[16:00:08] [Server thread/INFO]: [ItemsAdder] Found resourcepack folder: /plugins/ItemsAdder/data/resource_pack
[16:00:08] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Checking for online default resourcepack updates...
[16:00:09] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] No need to download default resourcepack. Cached file is up to date
[16:00:09] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Extracting resources from default resourcepack
[16:00:09] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] DONE extracting resources from default resourcepack
[16:00:09] [Server thread/INFO]: [ItemsAdder] Extracting default items from .jar
[16:00:09] [Server thread/INFO]: [ItemsAdder] DONE extracting default items from .jar
[16:00:09] [Server thread/INFO]: [ItemsAdder] Used 568/39648 available max font images.
[16:00:10] [Server thread/ERROR]: [ItemsAdder] IMPORTANT: if you add new liquids PLEASE RESTART THE SERVER or you won't see them.
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/rusty_sword.json' not found for item botany:rusty_sword
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/mortar_and_pestle.json' not found for item botany:mortar_and_pestle
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/weak_infusion_stone.json' not found for item botany:weak_infusion_stone
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/regular_infusion_stone.json' not found for item botany:regular_infusion_stone
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/strong_infusion_stone.json' not found for item botany:strong_infusion_stone
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/botany/models/auto_generated/extreme_infusion_stone.json' not found for item botany:extreme_infusion_stone
[16:00:10] [Server thread/ERROR]: [ItemsAdder] Model file '/home/taylor11/30783683/plugins/ItemsAdder/data/resource_pack/assets/itemsadder/models/auto_generated/bronze_ore.json' not found for item itemsadder:bronze_ore
[16:00:10] [Server thread/WARN]: [ItemsAdder] Task #737001 for ItemsAdder v2.1.19 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_272]
at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_272]
at dev.lone.itemsadder.j.a.b.a(SourceFile:138) ~[?:?]
at dev.lone.itemsadder.j.a.b.a(SourceFile:106) ~[?:?]
at dev.lone.itemsadder.j.a.b.<init>(SourceFile:98) ~[?:?]
at dev.lone.itemsadder.j.c.b(SourceFile:338) ~[?:?]
at dev.lone.itemsadder.f.b.a(SourceFile:1476) ~[?:?]
at dev.lone.itemsadder.e.y.a(SourceFile:60) ~[?:?]
at dev.lone.itemsadder.f.b.a(SourceFile:373) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.4.jar:git-Paper-262]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:regular_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:weak_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:regular_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botant:extreme_magic_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:regular_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:weak_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:regular_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:regular_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: botany:weak_magical_essence
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Result item botany:sun_stone not found in crafting recipe recipes.crafting_table.sun_stone, file /data/items_packs/botany/minerals.yml
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: itemsadder.chisel
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:cup_of_hot_water
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:plastic_plate
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:fossil
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:plastic_plate
[16:00:10] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:plastic_plate
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Can't find custom item named 'retr0craft:9carat_gold_dust' to complete the recipe registration
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Can't find custom item named 'retr0craft:9carat_gold_dust' to complete the recipe registration
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Can't find custom item named 'retr0craft:twentytwo_carrat_gold_dust' to complete the recipe registration
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Can't find custom item named 'retr0craft:twentytwo_carrat_gold_dust' to complete the recipe registration
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:end_ingot
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Ingredient not found: retr0craft:plastic_plate
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Loaded 1258 items
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Used 140/191 REAL block IDs.
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Used 3/63 REAL_TRANSPARENT block IDs.
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Loaded 51 categories
[16:00:11] [Craft Scheduler Thread - 2605/INFO]: [ItemsAdder] Loaded items and stuff in 2057ms

 - Server version: paper 1.16.4
 - Client version: vanilla 1.16.4
 - Plugin version: latest

**Comment by LoneDev6** [comment]
Hello, set generate: true instead of false when you want itemsadder to autogenerate the item model based on your textures.
That's the problem.

Let me know if you have any other problem.

Anyway I noticed you're configuring the plugin via web panel and/or FTP, this is tedious and leads to errors like this.
Please consider reading this tutorial: https://itemsadder.plugin.ga/plugin-usage/tips-for-fastest-usage
And using my official tool to edit your files instead of using external text editors: https://itemsadder.plugin.ga/files-editor

**Comment by tlw12344** [comment]
ive done what you've said but im still getting no textures but i am getting an error each time i do /iazip
[19:55:55] [Server thread/WARN]: [ItemsAdder] Task #87979 for ItemsAdder v2.1.20 generated an exception
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_272]
at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_272]
at dev.lone.itemsadder.j.a.b.a(SourceFile:138) ~[?:?]
at dev.lone.itemsadder.j.a.b.a(SourceFile:106) ~[?:?]
at dev.lone.itemsadder.j.a.b.<init>(SourceFile:98) ~[?:?]
at dev.lone.itemsadder.j.c.b(SourceFile:338) ~[?:?]
at dev.lone.itemsadder.f.b.a(SourceFile:1476) ~[?:?]
at dev.lone.itemsadder.e.y.a(SourceFile:60) ~[?:?]
at dev.lone.itemsadder.f.b.a(SourceFile:373) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.4.jar:git-Paper-262]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1297) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-262]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-262]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Ingredient not found: itemsadder.chisel
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Loaded 1258 items
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Used 140/191 REAL block IDs.
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Used 3/63 REAL_TRANSPARENT block IDs.
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Loaded 51 categories
[19:55:55] [Craft Scheduler Thread - 1635/INFO]: [ItemsAdder] Loaded items and stuff in 2923ms

**Comment by LoneDev6** [comment]
Please send me your complete server log.
Surely something else failed on top of this error.
I suspect you forgot to set a texture of one of the items but I can't say which one. To know which item has missing texture you have to enable logging:
```yml
    log-files-loading: true
    log-items-loading: true
```
