### ISSUE TITLE
[BUG] Plugin dont load :/

### ISSUE THREAD

**Issue by 6742123910210** [LoneDev6/ItemsAdder#523]
java.lang.IllegalStateException: FastInv is already registered
        at fr.mrmicky.fastinv.FastInvManager.register(FastInvManager.java:37) ~[?:?]
        at dev.lone.itemsadder.Main.onEnable(SourceFile:200) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[13:47:10 INFO]: [ItemsAdder] Disabling ItemsAdder v2.1.20

I get this error

**Comment by LoneDev6** [comment]
Update LoneLibs
