### ISSUE TITLE
[BUG] chunk corruption

### ISSUE THREAD

**Issue by DabbingEevee** [LoneDev6/ItemsAdder#527]
**Describe the bug**
chunk corruption happening occasionally

**To Reproduce**
unknown. issue has happened twice now. it happened the 2nd time when /iazip was issued

**Expected behavior**
uncorrupted chunks

**Screenshots**
n/a

**Info (please complete the following information):**
 - Server version: paper 1.16.3
 - Client version: not relevent
 - Plugin version: 2.1.20

**Additional context**
[15:22:09 ERROR]: [ItemsAdder] Corrupted region data! Moving it into 'corrupted_data' folder: /home/gamer/ns4/./world//region_custom_blocks//r.0.-1.nbt
[15:22:09 WARN]: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Exception while reading a NBT File!
[15:22:09 WARN]: 	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:59)
[15:22:09 WARN]: 	at dev.lone.LoneLibs.nbt.nbtapi.NBTFile.<init>(NBTFile.java:36)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.c.b.b.<init>(SourceFile:26)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.c.b.a.<init>(SourceFile:22)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.c.d.b(SourceFile:147)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.c.b.c(SourceFile:29)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.b.a(SourceFile:2011)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:159)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:247)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:438)
[15:22:09 WARN]: 	at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:378)
[15:22:09 WARN]: 	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37)
[15:22:09 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:22:09 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:22:09 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.a(World.java:611)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.a(World.java:448)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.a(World.java:518)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockFireAbstract.fireExtinguished(BlockFireAbstract.java:120)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:71)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockFire.onPlace(BlockFire.java:348)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:56)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.onPlace(BlockBase.java:557)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:524)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.a(World.java:395)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.World.setTypeUpdate(World.java:557)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.FluidTypeLava.b(FluidTypeLava.java:49)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.Fluid.b(Fluid.java:53)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockFluids.tick(BlockFluids.java:41)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:569)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:847)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:22:09 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:22:09 WARN]: Caused by: dev.lone.LoneLibs.nbt.nbtapi.NbtApiException: Error while calling the method 'a', loaded: true, Enum: NBTFILE_READ
[15:22:09 WARN]: 	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:158)
[15:22:09 WARN]: 	at dev.lone.LoneLibs.nbt.nbtapi.NBTReflectionUtil.readNBT(NBTReflectionUtil.java:57)
[15:22:09 WARN]: 	... 46 more
[15:22:09 WARN]: Caused by: java.lang.reflect.InvocationTargetException
[15:22:09 WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
[15:22:09 WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:22:09 WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[15:22:09 WARN]: 	at dev.lone.LoneLibs.nbt.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:156)
[15:22:09 WARN]: 	... 47 more
[15:22:09 WARN]: Caused by: net.minecraft.server.v1_16_R2.ReportedException: Loading NBT data
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:475)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.access$200(NBTTagCompound.java:27)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:53)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound$1.b(NBTTagCompound.java:38)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:176)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:145)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:58)
[15:22:09 WARN]: 	... 51 more
[15:22:09 WARN]: Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
[15:22:09 WARN]: 	at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)
[15:22:09 WARN]: 	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
[15:22:09 WARN]: 	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
[15:22:09 WARN]: 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
[15:22:09 WARN]: 	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
[15:22:09 WARN]: 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
[15:22:09 WARN]: 	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
[15:22:09 WARN]: 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
[15:22:09 WARN]: 	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagString$1.b(NBTTagString.java:14)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagString$1.b(NBTTagString.java:10)
[15:22:09 WARN]: 	at net.minecraft.server.v1_16_R2.NBTTagCompound.b(NBTTagCompound.java:468)
[15:22:09 WARN]: 	... 69 more
[15:22:09 ERROR]: Could not pass event BlockPhysicsEvent to ItemsAdder v2.1.20
java.lang.NullPointerException: null
	at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:162) ~[?:?]
	at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:247) ~[?:?]
	at dev.lone.itemsadder.f.f.a.b.b.a.b.b(SourceFile:438) ~[?:?]
	at dev.lone.itemsadder.f.f.a.b.b.a.b.a(SourceFile:378) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-253]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.a(World.java:611) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.applyPhysics(World.java:566) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.WorldServer.update(WorldServer.java:2183) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.notifyAndUpdatePhysics(World.java:481) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.a(World.java:448) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.a(World.java:518) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockFireAbstract.fireExtinguished(BlockFireAbstract.java:120) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:71) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockFire.onPlace(BlockFire.java:348) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockFireAbstract.onPlace(BlockFireAbstract.java:56) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.onPlace(BlockBase.java:557) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.Chunk.setType(Chunk.java:524) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.a(World.java:395) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.setTypeAndData(World.java:358) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.World.setTypeUpdate(World.java:557) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.FluidTypeLava.b(FluidTypeLava.java:49) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.Fluid.b(Fluid.java:53) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockFluids.tick(BlockFluids.java:41) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:569) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:705) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.lambda$tickChunks$14(ChunkProviderServer.java:847) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.PlayerChunkMap.forEachVisibleChunk(PlayerChunkMap.java:628) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:825) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:743) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-253]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LoneDev6** [comment]
Did your server crash recently?
Did you stop the server without letting it save data?

Seems somehow region 0 -1 saving got interrupted in a previous server run.
It's likely to be around the server spawn since its coords are low (region coords 0, -1).

Let me know

**Comment by DabbingEevee** [comment]
the server have never crashed or been forced shutdown.

**Comment by LoneDev6** [comment]
Can I get the full server log when you got this problem?
