### ISSUE TITLE
Custom Crafting Null Exception[BUG] 

### ISSUE THREAD

**Issue by diontimmer** [LoneDev6/ItemsAdder#529]
**Describe the bug**
Custom crafting recipes seem to have stopped working suddenly. The crafting output seems to be blank after putting the items in. upon clicking the output it shows an error in the console.
**To Reproduce**
Create a recipe through itemsadder, upon crafting nothing would show up in the crafting output for me anymore even though the recipes were working beforehand.

**Expected behavior**
The output item should show up and there should be no error in console when clicking the blank output.

**Screenshots**
here is a paste of the error
```
[05:05:44 ERROR]: Could not pass event InventoryClickEvent to ItemsAdder v2.1.20
java.lang.NullPointerException: null
        at dev.lone.itemsadder.f.j.c.a.f(SourceFile:53) ~[?:?]
        at dev.lone.itemsadder.f.j.c.b.a(SourceFile:70) ~[?:?]
        at dev.lone.itemsadder.f.j.c.c.a(SourceFile:138) ~[?:?]
        at dev.lone.itemsadder.f.j.c.c.a(SourceFile:161) ~[?:?]
        at dev.lone.itemsadder.f.j.c.c.j(SourceFile:259) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Purpur-830]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Purpur-830]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Purpur-830]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2579) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1207) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1200) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1337) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.4.jar:git-Purpur-830]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Purpur-830]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Info (please complete the following information):**
 - Server version: Purpur 1.16.4
 - Client version: Minecraft 1.16.4
 - Plugin version: ItemsAdder v2.1.20

**Comment by diontimmer** [comment]
It seems to be vanilla recipes as well

**Comment by diontimmer** [comment]
Error being discussed more clear elsewhere
