### ISSUE TITLE
[BUG] Could not pass event ItemsAdderFirstLoadEvent to ItemsAdder v2.1.21

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#544]
```

[06:01:24] [Server thread/ERROR]: Could not pass event ItemsAdderFirstLoadEvent to ItemsAdder v2.1.21
--
1548 | java.lang.AbstractMethodError: Missing implementation of resolved method 'abstract java.lang.String getIdentifier()' of abstract class me.clip.placeholderapi.expansion.PlaceholderExpansion.
1549 | at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.register(LocalExpansionManager.java:158) ~[?:?]
1550 | at me.clip.placeholderapi.expansion.PlaceholderExpansion.register(PlaceholderExpansion.java:132) ~[?:?]
1551 | at dev.lone.itemsadder.Main.b(SourceFile:324) ~[?:?]
1552 | at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.3.jar:git-Paper-253]
1553 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
1554 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
1555 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
1556 | at dev.lone.itemsadder.f.b.i(SourceFile:1378) ~[?:?]
1557 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
1558 | at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-253]
1559 | at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-253]
1560 | at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-253]
1561 | at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-253]
1562 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-253]
1563 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]


```

Il log intero: https://log.mtxserv.com/NA26nef#L1547

**Comment by LoneDev6** [comment]
Controlla di aver aggiornato PlaceholderAPI
https://www.spigotmc.org/resources/placeholderapi.6245/

**Comment by Fargus5** [comment]
> Controlla di aver aggiornato PlaceholderAPI
> https://www.spigotmc.org/resources/placeholderapi.6245/

Si si ho l'ultima certo

**Comment by LoneDev6** [comment]
continua su discord.

related to https://github.com/LoneDev6/ItemsAdder/issues/540
