### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mr200tt** [LoneDev6/ItemsAdder#551]
when i do /itemsadder:iakill

i get this:

[19:22:03 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'itemsadder:iakill' in plugin ItemsAdder v2.1.19
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
Caused by: java.lang.NullPointerException
        at dev.lone.itemsadder.f.b.d(SourceFile:1905) ~[?:?]
        at dev.lone.itemsadder.e.l.onCommand(SourceFile:74) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Paper-1.14.4-b243.jar:git-Paper-243]
        ... 17 more

**Comment by LoneDev6** [comment]
Please follow the bug report template, don't erase everything
