### ISSUE TITLE
[BUG] The plugin is not working anymore....

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/ItemsAdder#561]
**Describe the bug**
This afternoon the plugin was working super well when i left my server (i'm alone on it).
I just joined it again 5 mins ago and the plugin doesn't work anymore...

Furthermore, i can't access the /ia (menu), i can't access to the /iaget or /iagive (or all commands) (THE ONLY command that is working is /iazip)
and when i pose block it doesn't give me the texture on the ground when i pose it BUT i shows the texture in my hand correctly. 
(as u can see)

![2020-12-15_02 38 16](https://user-images.githubusercontent.com/57060565/102157074-222bda00-3e7f-11eb-8357-559b74b02319.png)

![2020-12-15_02 42 30](https://user-images.githubusercontent.com/57060565/102157151-42f42f80-3e7f-11eb-8e37-ba5a02990764.png)

**These are my logs :**

> [02:36:26] [Server thread/INFO]: Valouu issued server command: /ia
> [02:36:26] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ia' in plugin ItemsAdder v2.1.18
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1498) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.NullPointerException
at dev.lone.itemsadder.e.a.onCommand(SourceFile:54) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
... 17 more

**THESE ARE MY LOGS WHEN I EXECUTE /IAZIP**

> [02:44:35] [Server thread/INFO]: Valouu issued server command: /iazip
> [02:44:35] [Server thread/INFO]: [CronyItems] Started self-host webserver on port: 40101
> [02:44:35] [Server thread/INFO]: [CronyItems] Found resourcepack folder: /home/container/plugins/ItemsAdder/data/resource_pack
> [02:44:35] [Craft Scheduler Thread - 9/INFO]: java.net.SocketException: Socket closed
> [02:44:35] [Craft Scheduler Thread - 46/INFO]: [CronyItems] Checking for online default resourcepack updates...
> [02:44:36] [Craft Scheduler Thread - 46/INFO]: [CronyItems] No need to download default resourcepack. Cached file is up to date
> [02:44:36] [Craft Scheduler Thread - 46/INFO]: [CronyItems] Extracting resources from default resourcepack
> [02:44:36] [Craft Scheduler Thread - 46/INFO]: [CronyItems] DONE extracting resources from default resourcepack
> [02:44:36] [Server thread/INFO]: [CronyItems] Extracting default items from .jar
> [02:44:36] [Server thread/INFO]: [CronyItems] DONE extracting default items from .jar
> [02:44:36] [Server thread/INFO]: [CronyItems] Used 597/13216 available max font images.
> [02:44:36] [Server thread/INFO]: [CronyItems] Detected HUD: mana_bar
> [02:44:36] [Server thread/INFO]: [CronyItems] Skip disabled HUD
> [02:44:36] [Server thread/INFO]: [CronyItems] Detected HUD: thirst_bar
> [02:44:36] [Server thread/INFO]: [CronyItems] Skip disabled HUD
> [02:44:36] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "In"
> [02:44:36] [Server thread/WARN]: at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
> [02:44:36] [Server thread/WARN]: at java.lang.Integer.parseInt(Integer.java:580)
> [02:44:36] [Server thread/WARN]: at java.lang.Integer.valueOf(Integer.java:740)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.l.n.a(SourceFile:140)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.l.n.a(SourceFile:163)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:631)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:348)
> [02:44:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83)
> [02:44:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
> [02:44:36] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [02:44:36] [Server thread/ERROR]: [ItemsAdder] Error loading the plugin, something is not configured right or an exception occured. More detail:
> [02:44:36] [Server thread/WARN]: java.lang.NullPointerException
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.l.n.a(SourceFile:164)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:631)
> [02:44:36] [Server thread/WARN]: at dev.lone.itemsadder.f.b.a(SourceFile:348)
> [02:44:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:83)
> [02:44:36] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984)
> [02:44:36] [Server thread/WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824)
> [02:44:36] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [02:44:36] [Craft Scheduler Thread - 61/INFO]: [CronyItems] Compressing resource_pack ...
> [02:44:39] [Craft Scheduler Thread - 61/INFO]: [ItemsAdder] §a Resource pack successfully compressed.
> [02:44:39] [Craft Scheduler Thread - 61/INFO]: [CronyItems] Checking resourcepack url... http://51.91.36.177:40101/pack.zip
> [02:44:39] [Craft Scheduler Thread - 61/INFO]: [CronyItems] Resourcepack URL should be valid. using self-host. Url: http://51.91.36.177:40101/pack.zip
> [02:44:39] [Craft Scheduler Thread - 61/INFO]: [CronyItems] Applying pack to every player...
> [02:44:39] [Craft Scheduler Thread - 61/INFO]: [CronyItems] Applied pack to 1 players

**To Reproduce**
I don't know, it started suddenly when I didn't touch anything...
The only thing i did was a /iazip...

**Info (please complete the following information):**
 - Server version: Spigot 1.15.2
 - Client version: The minecraft launcher (1.15.2)
 - Plugin version: 2.1.18

**Comment by LoneDev6** [comment]
Please install the latest version of the plugin, you're running an old one.
Update ItemsAdder, protocollib and lonelibs.

Let me know if the problem is still there after you updated the plugin, thanks and have a nice day.

**Comment by LoneDev6** [comment]
Anyway I read your log and seems something failed to load.
```
[02:44:36] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "In"
```

Somewhere in your configs you set In where the plugin was expecting a number.

I suggest you to enable all log options in config.yml and see what's the last correctly loaded item/thing. The next one is the failed one.
If you can't manage to identify it: update to the latest version of itemsadder and send me the updated log or I cannot tell you what it can be as the provided log is old.
