### ISSUE TITLE
[BUG] interact event crashed server

### ISSUE THREAD

**Issue by R-Josef** [LoneDev6/ItemsAdder#565]
**Describe the bug**
NullPointerException if define a interact.right event on a sword, but player click on nothing.

**To Reproduce**
1. Define a interact.right event on a sword
2. Look up and right click the sky (do not click on blocks)
3. See error

**Expected behavior**
I think this should not print error to console, if player click on air, nothing should be happen.

**Info (please complete the following information):**
 - Server version: tuinity 1.16.4
 - Client version: vanilla 1.16.4
 - Plugin version: v2.1.22b

**Additional context**
Here is my sword config:
```yaml
  megumi_staff:
    display_name: '&4&l惠惠的法杖'
    permission: megumi_staff
    resource:
      material: WOODEN_SWORD
      generate: false
      model_path: item/megumi_staff
    durability:
      max_custom_durability: 59
    attribute_modifiers:
      mainhand:
        attackDamage: 8.0
        attackSpeed: 1.5
    events:
      interact:
        left:
          play_particle:
            name: SPELL_WITCH
        right:
          play_particle:
            name: SPELL_WITCH
          explosion:
            power: 2
            fire: false
            break_blocks: false
          decrement_durability:
            amount: 1
      attack:
        play_particle:
          name: SNEEZE
```
Here is the error:
```
[03:04:43 ERROR]: Could not pass event PlayerInteractEvent to ItemsAdder v2.1.22b
java.lang.NullPointerException: null
        at dev.lone.itemsadder.Core.f.c.a.h.a(SourceFile:39) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.a.a.b.e(SourceFile:49) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.b.g.g(SourceFile:175) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.b.g.i(SourceFile:66) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.c.a(SourceFile:138) ~[?:?]
        at dev.lone.itemsadder.Core.f.c.c.m(SourceFile:208) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:470) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:466) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1589) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.4.jar:git-Tuinity-cc34294]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by LoneDev6** [comment]
This error is triggered because no block is interacted, you're interacting air and the plugin cannot find where to make the explotion.
I removed that error in the new update, keep in mind that the staff will make explosions only on interacted blocks.
