### ISSUE TITLE
random error, possibly ufo related

### ISSUE THREAD

**Issue by PhanaticD** [LoneDev6/ItemsAdder#57]
```
[17:22:06 WARN]: [ItemsAdder] Task #7857 for ItemsAdder v1.1.34 generated an exception
java.lang.NullPointerException: null
        at dev.lone.itemsadder.c.c.B.a(Unknown Source) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[bvival.jar:git-Purpur-295]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1178) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:426) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1105) ~[bvival.jar:git-Purpur-295]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:932) ~[bvival.jar:git-Purpur-295]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by LoneDev6** [comment]
Does this happens also with Paper?

**Comment by PhanaticD** [comment]
i dont know how to reproduce it

**Comment by LoneDev6** [comment]
Does this still happens? on latest version
