### ISSUE TITLE
BlockFadeEvent issue.

### ISSUE THREAD

**Issue by MothGirlMusic** [LoneDev6/ItemsAdder#58]
not sure what causes it. just happens every so often so it must be some incorrect "hook" in one of the items... or listeners. but no one's reported anything wrong. so it must not be all that "mission critical" to any of the items.
```
[15:37:27] [Server thread/ERROR]: Could not pass event BlockFadeEvent to ItemsAdder v1.1.36
org.bukkit.event.EventException: null
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockFadeEvent(CraftEventFactory.java:674) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.BlockSoil.fade(BlockSoil.java:101) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.BlockSoil.tick(BlockSoil.java:63) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.Block.c(Block.java:355) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.IBlockData.b(SourceFile:269) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:439) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.lambda$9(ChunkProviderServer.java:422) ~[server.jar:git-Spigot-94af569-a3fdef8]
    at org.bukkit.craftbukkit.libs.it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) [server.jar:git-Spigot-94af569-a3fdef8]
    at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickChunks(ChunkProviderServer.java:364) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.ChunkProviderServer.tick(ChunkProviderServer.java:334) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:259) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [server.jar:git-Spigot-94af569-a3fdef8]
    at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [server.jar:git-Spigot-94af569-a3fdef8]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException
    at dev.lone.itemsadder.c.c.t.a(Unknown Source) ~[ItemsAdder.jar:?]
    at sun.reflect.GeneratedMethodAccessor672.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[server.jar:git-Spigot-94af569-a3fdef8]
    ... 20 more
```

**Comment by LoneDev6** [comment]
Still happening? I didn't ever got that error, maybe was because of a Spigot bug

**Comment by MothGirlMusic** [comment]
no, not that i can tell. can probably close this issue and i'll let you know if it ever pops up again
