### ISSUE TITLE
[BUG] Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by Fargus5** [LoneDev6/ItemsAdder#587]
```

[08:58:01] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ItemsAdder v2.1.24
--
2879 | java.lang.NullPointerException: null
2880 | at dev.lone.itemsadder.Core.f.a.c.a.a.a(SourceFile:428) ~[?:?]
2881 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2111.execute(Unknown Source) ~[?:?]
2882 | at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-253]
2883 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
2884 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
2885 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
2886 | at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:801) ~[patched_1.16.3.jar:git-Paper-253]
2887 | at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1491) ~[patched_1.16.3.jar:git-Paper-253]
2888 | at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1420) ~[patched_1.16.3.jar:git-Paper-253]
2889 | at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.3.jar:git-Paper-253]
2890 | at net.minecraft.server.v1_16_R2.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.16.3.jar:git-Paper-253]
2891 | at net.minecraft.server.v1_16_R2.EntityHuman.attack(EntityHuman.java:1087) ~[patched_1.16.3.jar:git-Paper-253]
2892 | at net.minecraft.server.v1_16_R2.EntityPlayer.attack(EntityPlayer.java:1828) ~[patched_1.16.3.jar:git-Paper-253]
2893 | at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2146) ~[patched_1.16.3.jar:git-Paper-253]
2894 | at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.3.jar:git-Paper-253]
2895 | at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.3.jar:git-Paper-253]
2896 | at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-253]
2897 | at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
2898 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
2899 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
2900 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
2901 | at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
2902 | at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
2903 | at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
2904 | at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
2905 | at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
2906 | at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
2907 | at java.lang.Thread.run(Thread.java:834) [?:?]


```

**Comment by Fargus5** [comment]
https://log.mtxserv.com/VRZXLWa#L2128

**Comment by LoneDev6** [comment]
Grazie  https://github.com/LoneDev6/ItemsAdder/issues/586

**Comment by Fargus5** [comment]
@LoneDev6 Matteo il problema sembra persistere.

https://log.mtxserv.com/yvRdMiE

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 Matteo il problema sembra persistere.
> 
> https://log.mtxserv.com/yvRdMiE

Grazie! E' un altro errore legato ad un problema a cui non avevo pensato, lo sistemo oggi
