### ISSUE TITLE
Error getting on Vehicles

### ISSUE THREAD

**Issue by Linebeck** [LoneDev6/ItemsAdder#68]
This seems to be client sided:

[22:06:15] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1298) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:739) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1132) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-219]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[22:06:16] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1298) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:739) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1132) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-219]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[22:06:16] [Server thread/INFO]: Komagire issued server command: /heal
[22:06:17] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1298) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:739) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1132) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-219]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
[22:06:18] [Server thread/INFO]: [Hero] Explod!ngMe|on: i hate diroite
[22:06:32] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChunkMapDistance.b(ChunkMapDistance.java:245) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:1298) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.ChunkProviderServer.movePlayer(ChunkProviderServer.java:739) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1132) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-219]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-219]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

Any ideas?

**Comment by LoneDev6** [comment]
Can you please send me **/version** command output? 
Also with "This seems to be client sided" what do you mean?

Thanks

**Comment by Linebeck** [comment]
![image](https://user-images.githubusercontent.com/25122665/67986835-58b67f00-fc02-11e9-8ed2-1b8f42bf588c.png)

I mean that it only does it for me. When I log off and back in, it's like i never placed the vehicle. Players don't see me place it.

**Comment by LoneDev6** [comment]
Can you please test on a local server with only itemsadder installed + protocollib?

Thanks
